### ISSUE TITLE
Support for Tizen 4.0

### ISSUE THREAD

**Issue by davystrong** [flutter-tizen/flutter-tizen#10]
The Samsung Galaxy watch, from only two years ago, still uses Tizen 4.0. Could this also be supported?

**Comment by swift-kim** [comment]
The ecore_wl2 APIs that are currently being used by the embedder are not supported by Tizen 4.0 which only supports ecore_wl. Porting with ecore_wl APIs didn't go very successfully when we tried two months ago. We'll continue to find the way to run Flutter on Tizen 4.0 devices.

cc @xuelian-bai @xiaowei-guan

**Comment by davystrong** [comment]
Thanks for the quick reply! I hope you can find a way, because that would be really nice to have.

**Comment by swift-kim** [comment]
I'm glad to hear that you were actually trying to port it by yourself! I'll let you know if anything is found soon.

**Comment by swift-kim** [comment]
Sorry for the delay!

#29 has landed and flutter-tizen is now compatible with Tizen 4.0. You may try out by updating flutter-tizen to the latest (`git pull`) although the new engine is not very stable yet.

**Comment by davystrong** [comment]
That's great! I've tried it out and it seems to work well. Thanks for prioritising this - I've been hoping for Flutter on Tizen since I started using it!
