### ISSUE TITLE
Has anybody been able to compile a tpk while using device_info_tizen or battery_tizen without errors?

### ISSUE THREAD

**Issue by Brendan-H** [flutter-tizen/flutter-tizen#118]
Even when I compile with the boilerplate code, and simply just add device_info_tizen or battery_tizen to my pubspec.yaml, I get a ridiculous amount of errors, all pointing to multiple files that supposedly dont exist (they do) As soon as I remove the dependencies, my app builds fine. Has anybody had anything like this happen to them? I haven't included any error codes as I'd like to see if this is an error with the plugin, or something on my end.

**Comment by jtmuller5** [comment]
Yes! I just had this problem and it turned out that my project pathway contained spaces.

I refactored to get rid of the spaces and everything started working again.

 (ex. H:/Flutter Apps/Tizen App/project -> H:/FlutterApps/TizenApp/project)

**Comment by Brendan-H** [comment]
@jtmuller5 I dont know exactly how I fixed it, but your comment helped to make me rethink my folders! Since I was too lazy to set up visual studio, I just created a subfolder under my AndroidStudioProjects folder, which is probably the cause. Because of this, I moved my app to a subfolder just under C:/ (H:/ for you) After this, I decided to try 'flutter pub add device_info_tizen', which not only added device_info_tizen, but also device_info_platform_interface, and  plugin_platform_interface 2.0.0. Missing dependencies that weren't listed in the documentation could have also been the cause. Either way, thanks for the help!

**Comment by swift-kim** [comment]
Dependent packages are automatically resolved by the Dart SDK so you don't typically need to care about them. If you open the `.packages` (or `.dart_tool\package_config.json`) file in your project directory, you will see the absolute paths to the resolved packages which are cached in your local drive (probably under `AppData\Local\Pub`).

I tried to reproduce this error but it wasn't quite successful. Please leave a comment or open a new issue if anybody experienced similar errors.

**Comment by swift-kim** [comment]
Now I figured out how to reproduce the error you mentioned. It probably look like:

```
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

lib/main.dart:1:8: Error: Error when reading '../../../flutter-tizen/flutter/packages/flutter/lib/material.dart': No such file or directory
import 'package:flutter/material.dart';
       ^
lib/main.dart:4:8: Error: Error when reading '../../../flutter-tizen/flutter/packages/flutter/lib/services.dart': No such file or directory
import 'package:flutter/services.dart';
       ^
../lib/plugin_test.dart:8:8: Error: Error when reading '../../../flutter-tizen/flutter/packages/flutter/lib/services.dart': No such file or directory
import 'package:flutter/services.dart';
       ^
lib/main.dart:11:21: Error: Type 'StatefulWidget' not found.
class MyApp extends StatefulWidget {
                    ^^^^^^^^^^^^^^
...

../lib/plugin_test.dart:11:16: Error: 'MethodChannel' isn't a type.
  static const MethodChannel _channel =
               ^^^^^^^^^^^^^
Exception
Building a Tizen application in release mode...                    929ms
The build failed.
```

This error occurs when you

1. Create an app project.
2. Move the SDK (flutter-tizen) to another directory.
3. Try to build the project.

This is because the project's packages file (`.packages`) stores paths to packages provided by the SDK and those paths are not updated properly when the SDK is moved.

The solution is to run `flutter-tizen pub get` once in the project directory after moving the SDK.
