### ISSUE TITLE
tpkroot is not generated when building native apps on Windows

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#121]
https://github.com/flutter-tizen/flutter-tizen/blob/194470d810cfdd9e2aa445554cb9d7c1529de813/lib/tizen_build_target.dart#L737-L738

Somehow the unzip function doesn't work on Windows and as a result `flutter-tizen build tpk --analyze-size` throws a FileSystemException.

```
$ flutter-tizen create --tizen-language cpp --platforms android native_app
$ cd native_app
$ flutter-tizen build tpk --analyze-size
The "--device-profile" option is not set. Specify the target profile for which you want to build your app.

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

The Wearable profile is used for signing.
Building a Tizen application in release mode...                    75.4s
✓ Built build\tizen\tpk\com.example.native_app-1.0.0.tpk (6.1MB).
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

FileSystemException: Directory listing failed, path = 'E:\dummy\native_app\build\tizen\tpk\tpkroot\*' (OS Error: 지정된 경로를 찾을 수 없습니다.
, errno = 3)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      SizeAnalyzer._parseDirectory (package:flutter_tools/src/base/analyze_size.dart:153:39)
#5      SizeAnalyzer.analyzeAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:50:41)
#6      TizenBuilder.buildTpk (package:flutter_tizen/tizen_builder.dart:176:61)
<asynchronous suspension>
...
```

**Comment by HakkyuKim** [comment]
Sorry, clicked the wrong button by mistake. 

On Windows, `unzip` method writes decoded objects to the target directory only for those recognized as a "file" type. Somehow objects in native build tpk are not perceived as files. I've also tested with another library: [archive](https://pub.dev/packages/archive). I will look into this.

**Comment by HakkyuKim** [comment]
There seems to be an issue in the TPK format built on Windows host PC, I'm asking the SDK team about it.

[Code](https://github.com/brendan-duncan/archive/blob/9de7a0544457c6aba755ccb65abb41b0dc1db70d/lib/src/zip_decoder.dart#L44-L50) that causes to fail the unzipping process in the [archive](https://pub.dev/packages/archive) package.
