### ISSUE TITLE
Choosing rootstrap

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/flutter-tizen#128]
When executing the run or build command, flutter-tizen must select the root strap appropriately according to the device profile.

**As-is**

- mobile profile

```bash
$ flutter-tizen build tpk --device-profile mobile -v
...
[  +15 ms] executing: /home/boram/tizen-studio/tools/ide/bin/tizen build-native -a arm -C Release -c llvm-10.0 -r wearable-4.0-arm.flutter -e -lflutter_tizen_mobile
...
[+9125 ms] [PLATFORM] Wearable-4.0
                    [ARCHITECTURE] armel
                    [COMPILER] LLVM-10.0
                    [CONFIGURATION] Release
                    [SBI] prdefine options = 
                    [SBI] command : /bin/sh -c /usr/bin/make -f "/home/boram/tizen-studio/tools/ide/resources/native/Build/makefile" -r 
```

- tv profile

```bash
$ flutter-tizen build -v --devicePprofile tv
...
[  +16 ms] executing: /home/boram/tizen-studio/tools/ide/bin/tizen build-native -a arm -C Release -c llvm-10.0 -r wearable-4.0-arm.flutter -e -lflutter_tizen_t
...
[+8907 ms] [PLATFORM] Wearable-4.0
                    [ARCHITECTURE] armel
                    [COMPILER] LLVM-10.0
                    [CONFIGURATION] Release
                    [SBI] prdefine options = 
                    [SBI] command : /bin/sh -c /usr/bin/make -f "/home/boram/tizen-studio/tools/ide/resources/native/Build/makefile" -r 
```

**Additional related matters**
- As far as I know, TV profiles do not have official public native rootstraps. Should we use common rootstrap for tv profile?
- Tizen Studio provides extensions to support rootstraps for iot profiles.

**Comment by bbrto21** [comment]
And even if specify --debug option, the host seems to build as release mode (CC flutter-tizen/engine#95)
```
$ flutter-tizen build tpk --device-profile tv -v --debug
...
[  +73 ms] executing: /usr/bin/dotnet build -c Release -o /home/boram/Work/f-project/plugins/packages/camera/example/build/tizen/tpk/ /p:FlutterEmbeddingVersion=1.8.0
...
```

**Comment by swift-kim** [comment]
> ```
> /usr/bin/dotnet build -c Release
> ```

This was kind of intentional (only affects the C# compiler) but I'll clean it up as well.

**Comment by swift-kim** [comment]
There are too many cases we have to handle (3x3x2=18 or more)

- mobile, wearable, iot-headed
- arm, arm64, x86
- 4.0, 5.5

and I think we should dynamically generate the rootstrap definition when requested rather than using static definitions (`rootstrap/`). It would require some time for implementation/testing.
