### ISSUE TITLE
Document how to publish apps on the TV app store

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#137]
We need to fill the part in https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/publish-app.md.

**Comment by iandis** [comment]
publishing TV app to samsung seller 2.0 seems a little bit confusing for me. I was trying to upload my .tpk and the pre-test failed. It said my tpk needed to have <tv-info> in the tizen-manifest. I tried finding it online but found nothing helpful.

**Comment by swift-kim** [comment]
@iandis It looks like a temporary issue. I'll contact the person in charge in the TV division and let you know when I get a reply.

**Comment by swift-kim** [comment]
@iandis I got a response and they're going to fix the issue in a few days, but you can also try adding the following lines to your tizen-manifest.xml to work around the issue.

```xml
<tv-info api-version="8.8.0">
    <infolink>T-INFOLINK2021-1000</infolink>
</tv-info>
```

**Comment by iandis** [comment]
@swift-kim Thank you very much for the quick response😃!
