### ISSUE TITLE
Galaxy Store API checker failing APIs

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#140]
The API checker rejected the following symbols included in the new Flutter 2.2 engine binary.

```
OPENSSL_memory_get_size[libflutter_engine.so]
OPENSSL_memory_alloc[libflutter_engine.so]
sdallocx[libflutter_engine.so]
OPENSSL_memory_free[libflutter_engine.so]
```

The weak symbols were first added by https://boringssl.googlesource.com/boringssl/+/9ae40ce9ad7e2b1e0140dc98318bc742e8387f88

and changed by
https://boringssl.googlesource.com/boringssl/+/0cf14d3ec8d79b33bdaede1266a8c90595d03a05 and
https://boringssl.googlesource.com/boringssl/+/0313b59d5f950a05f2269811732bbbf204059da5.

As you can see in the commit log, providing real implementations for the weak symbols is optional (there are fallback implementations). So there's no need to export the symbols if we're not to inject sanitizer hooks to track memory allocations. However, they are always exported due to the existence of the attribute `__attribute__((weak))`, and the attribute cannot be overridden by adding `OPENSSL_*` to the local symbol list in the version script.

We need to either

- Add the symbols to the allowlists (need to discuss with the store team), or
- Temporarily modify `mem.c` to use only strong symbols.

Any thoughts, or other ways to work around?

**Comment by bwikbs** [comment]
> However, they are always exported due to the existence of the attribute __attribute__((weak)), and the attribute cannot be overridden by adding OPENSSL_* to the local symbol list in the version script.

It would be best if it could be solved with a version script... any progress?

**Comment by swift-kim** [comment]
No, changing the visibility of the symbols using the version script wasn't successful when I tried last time.

**Comment by bwikbs** [comment]
Oh.. that's so sad.. :cry:

**Comment by bwikbs** [comment]
Eh? I modified flutter_engine_exports.lst and just got the following result. Is this what we want?
```
{
  global:
    *Dart*;
  local:
    *;
};
```
before:
```
bwikbs@rat5:~/workspace/flutter-tizen/engine/src/out/linux_release_arm$ nm -CD libflutter_engine.so | grep OPENSSL_memory_get_size
         w OPENSSL_memory_get_size
bwikbs@rat5:~/workspace/flutter-tizen/engine/src/out/linux_release_arm$ nm -CD libflutter_engine.so | grep OPENSSL_memory_alloc
         w OPENSSL_memory_alloc
```

after:
```
bwikbs@rat5:~/workspace/flutter-tizen/engine/src/out/linux_release_arm$ nm -CD libflutter_engine.so | grep OPENSSL_memory_get_size
bwikbs@rat5:~/workspace/flutter-tizen/engine/src/out/linux_release_arm$ nm -CD libflutter_engine.so | grep OPENSSL_memory_alloc
```

**Comment by bwikbs** [comment]
Ummm... it doesn't work. just ignore it...

**Comment by bwikbs** [comment]
I give up :raised_hands: 
I've tried a few things... I only found that ``GN`` is pretty limited.

> Temporarily modify mem.c to use only strong symbols.

Why don't we use this until something else comes up. 
I just want to work on 2.2.1 quickly. :smile:

**Comment by swift-kim** [comment]
I have to first talk to Mr. Choi to decide how to deal with this issue, but I'm out of the office this week. This issue is quite complicated and hard to explain via e-mail.

**Comment by swift-kim** [comment]
This has been fixed by the store side. I'll submit a reverting PR soon.
