### ISSUE TITLE
Tizen toolchain - develop for Tizen devices (the doctor check crashed)

### ISSUE THREAD

**Issue by EbramTawfik** [flutter-tizen/flutter-tizen#142]
I am installing flutter-tizen and when I run `flutter-tizen doctor -v` I am getting this error
![image](https://user-images.githubusercontent.com/12788360/122273847-c1fe0b00-ce96-11eb-8795-9a78dee59a31.png)

`Tizen toolchain - develop for Tizen devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X NoSuchMethodError: The getter 'length' was called on null.
      Receiver: null
      Tried calling: length
    • #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
      #1      double._parse (dart:core-patch/double_patch.dart:95:19)
      #2      double.tryParse (dart:core-patch/double_patch.dart:118:45)
      #3      TizenValidator.validate (package:flutter_tizen/tizen_doctor.dart:88:38)
      #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #5      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #6      _rootRun (dart:async/zone.dart:1354:13)
      #7      _CustomZone.run (dart:async/zone.dart:1258:19)
      #8      _runZoned (dart:async/zone.dart:1788:10)
      #9      runZonedGuarded (dart:async/zone.dart:1776:12)
      #10     runZoned (dart:async/zone.dart:1707:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:203:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:307:47)
      #14     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:47)
      #15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:18)
      <asynchronous suspension>
      #16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
      <asynchronous suspension>
      #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
      <asynchronous suspension>
      #19     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
      <asynchronous suspension>
      #20     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
      <asynchronous suspension>
      #21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #22     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
      <asynchronous suspension>
      #23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
      <asynchronous suspension>
      #24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
      <asynchronous suspension>
      #25     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
      <asynchronous suspension>
      #28     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
      <asynchronous suspension>
      #29     main (package:flutter_tizen/executable.dart:79:3)
      <asynchronous suspension>`

**Comment by swift-kim** [comment]
Thank you for reporting!

I'll provide a fix for the error soon, but could you confirm that the file `sdk.version` exists in the `C:\tizen-studio` directory (or somewhere else if you installed Tizen Studio to a non-default location) and the file contains the `TIZEN_SDK_VERSION` key? If the file doesn't exist, could you try updating Tizen Studio by clicking the "Updates available" button in Package Manager and see if the file is generated after that?
