### ISSUE TITLE
Support multi package app

### ISSUE THREAD

**Issue by jkpu** [flutter-tizen/flutter-tizen#143]
I need flutter  multi package app (UI app + service app).
Tizen native app and .NET app supports multi package. 
Each project can refer to other project's code and can access files and database in the package installed directory.
It will be very helpful if Tizen flutter app supports multi package.

Native app
https://docs.tizen.org/application/native/tutorials/process/app-dev-process/#developing-multiple-projects-as-a-combined-package

.NET app
https://developer.samsung.com/tizen/blog/en-us/2019/01/04/how-to-package-ui-and-service-applications-together-and-perform-them

**Comment by pkosko** [comment]
I will check the feasibility of this feature if it is not assigned yet.

**Comment by swift-kim** [comment]
@jkpu How does the TPK with UI app + service app look like? Is the source code of the two apps compiled into a single executable under `bin` or do they have separate entrypoints?

**Comment by jkpu** [comment]
@swift-kim  No. UI app and service app has each own executable, they only package in same folder.
You can refer to native app example or .Net example in the above link.

following is the result I have tested with native UI app + service app 

```log
/opt/usr/home/owner/apps_rw/org.example.basicui
sh-3.2# ls -al
total 32
drwxr-xr-x   5 owner  users        4096 Jun 29 16:35 .
drwxr-x--- 106 owner  system_share 4096 Jun 29 16:35 ..
lrwxrwxrwx   1 app_fw app_fw         60 Jun 29 16:35 author-signature.xml -> /opt/usr/globalapps/org.example.basicui/author-signature.xml
lrwxrwxrwx   1 app_fw app_fw         43 Jun 29 16:35 bin -> /opt/usr/globalapps/org.example.basicui/bin
drwxr-sr-x   2 owner  system_share 4096 Jun 29 16:35 cache
drwxr-sr-x   2 owner  system_share 4096 Jun 29 16:35 data
lrwxrwxrwx   1 app_fw app_fw         43 Jun 29 16:35 lib -> /opt/usr/globalapps/org.example.basicui/lib
lrwxrwxrwx   1 app_fw app_fw         43 Jun 29 16:35 res -> /opt/usr/globalapps/org.example.basicui/res
drwxr-xr-x   3 owner  users        4096 Jun 29 16:35 shared
lrwxrwxrwx   1 app_fw app_fw         58 Jun 29 16:35 tizen-manifest.xml -> /opt/usr/globalapps/org.example.basicui/tizen-manifest.xml
sh-3.2# cat tizen-manifest.xml 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<manifest xmlns="http://tizen.org/ns/packages" api-version="4.0" package="org.example.basicui" version="1.0.0">
    <profile name="mobile"/>
    <ui-application appid="org.example.basicui" exec="basicui" launch_mode="single" multiple="false" nodisplay="false" taskmanage="true" type="capp">
        <label>basicui</label>
        <icon>basicui.png</icon>
    </ui-application>
    <service-application appid="org.example.testservice" exec="testservice" multiple="false" nodisplay="true" taskmanage="false" type="capp">
        <label>testservice</label>
        <icon>testservice.png</icon>
    </service-application>
</manifest>
sh-3.2# cd bin/
sh-3.2# ls -al
total 52
drwxr-xr-x 2 tizenglobalapp root  4096 Jun 29 16:35 .
drwxr-xr-x 6 tizenglobalapp root  4096 Jun 29 16:35 ..
-rwxr-xr-x 1 tizenglobalapp root 24192 Jun 29 16:35 basicui
-rwxr-xr-x 1 tizenglobalapp root 15032 Jun 29 16:35 testservice

```

**Comment by swift-kim** [comment]
There are many places in the tool that assume a single platform project for a single Flutter project and it would not be easy to re-design them all in a clean manner. If we really need to implement this feature, we will have to be very careful not to break any other even small features.

**Comment by swift-kim** [comment]
@pkosko I'll look into this issue if no progress has been made yet.

**Comment by pkosko** [comment]
hello, I've made significant progress.
Currently I have a working code for simple applications (ui + service) - https://github.com/pkosko/flutter-tizen/commit/2c9c385da2a4c5b99a864c476cfb88fa6f839c12
What I've already done:

- separate runners, flutter_assets and plugins for every application by adding appId suffix
- change the build method to support multiple packages in one tpk.
- add feature of scanning 'tizen_services' directory for existing sub applications
- running two apps together with 'flutter-tizen run'


For now, many cases still need to be checked, but I am doing progress every day. My TODO list:

- [ ] support automatic rebuild of services when the 'mother' application build is happening (in progress)
- [ ] check if everything works fine in applications using some plugins inside
- [ ] check also release mode of application build
- [ ] check and support hot reload of service application
- [ ] clean the code from any temporary logs 
- [ ] checking and optimization of 'common' application files to decrease redundancy
- [ ] (optional) add some flutter-tizen command supporting creation of service inside application


If you have any comments, please share.

**Comment by swift-kim** [comment]
@pkosko What I had in mind was to make the multi package app into a single Dart package, by creating multiple entry points in the Dart code (one for the UI app and one for the service app). In that way only small changes (tentatively) need to be made, like adding a template for a multi app project and adding a new (or modifying existing) build target to build a multi app project. That's why I mentioned this issue might depend on https://github.com/flutter-tizen/engine/pull/149.

**Comment by pkosko** [comment]
Sorry, I didn't notice the 'mention' and I focused on creating support for service on 'tizen' level, not 'dart'.

Now I need to make a deeper look at the concept explained in https://github.com/flutter-tizen/engine/issues/111 and https://github.com/flutter-tizen/engine/pull/149/, and make some checking on my side to understand it. 

For now I am not sure if I understand all your expectations regarding this issue. Could you please share the list of TODO things, that I can follow to avoid misunderstandings?

**Comment by swift-kim** [comment]
Sorry. I had to make the comment in this issue but not in the engine issue. (It's always good to share progress frequently if the work takes longer than you thought. :D)

I don't yet have a complete roadmap of what need to be done, and I just want to make things clear first. Do you know if I can create a single TPK which contains both UI and service apps within it by only using the Tizen CLI?

**Comment by pkosko** [comment]
I've used a https://developer.tizen.org/development/tizen-studio/web-tools/cli#Build_pack_multi_proj command as it is here: https://github.com/pkosko/flutter-tizen/commit/2c9c385da2a4c5b99a864c476cfb88fa6f839c12#diff-32efabcee487e07581c54bc0c3ac9e16b5401ebd7b15ad5337b96186fe36b41cR821 , but in my case the build targets were two Flutter-Tizen projects (one with UI and second a service only). CLI makes all necessary operations to pack them together into one TPK (including merging tizen-manifest.xml files and other resources).

**Comment by swift-kim** [comment]
Thanks. I have two basic template projects created by Tizen Studio:

```sh
$ ls -l
total 48
drwxr-xr-x 1 swift swift  4096 Jul 21 17:22 MultiApp
drwxr-xr-x 1 swift swift  4096 Jul 21 17:22 MultiAppService
```

and I used this command to package the projects into a TPK:

```
tizen build-app -m 'name: "m1", compiler: "llvm", configs:["Release"], arch:"arm"' -b 'name: "b1", methods: ["m1"], targets: ["MultiApp","MultiAppService"]' -p 'name: "test", targets: ["b1"]' -- .
```

The file `test_Wearable-6.0_i386.tpk` was generated as a result. I think something has gone wrong but I'll take a detailed look tomorrow.

**Comment by pkosko** [comment]
For the test project I used (notice that arch is inside a rootstraps property of method):

tizen build-app -m 'name:"m1", compiler: "llvm-10.0", configs: ["Debug"], rootstraps: [{name:"wearable-4.0-arm.flutter", platform:"wearable-4.0", arch:"arm"}]' -b 'name: "b1", methods: ["m1"], targets: ["test_project"]' -p 'name: "test", targets:["b1"]'
this makes an arm tpk.


An important conclusions from my work was that to pass additional linker flags, it is needed to use a 'hidden' option of rootstrap - 'extraoption:' (as it is [here](https://github.com/pkosko/flutter-tizen/commit/2c9c385da2a4c5b99a864c476cfb88fa6f839c12#diff-32efabcee487e07581c54bc0c3ac9e16b5401ebd7b15ad5337b96186fe36b41cR801)). This is not documented behaviour, but I found it in CLI code.

**Comment by swift-kim** [comment]
So my design is simple:

- There's one Flutter project, and the project contains two Tizen projects inside its `tizen` directory.
- The Tizen projects share the same Dart code. That is, only a single set of `flutter_assets` and `libapp.so` is generated.
- The Dart code contains two entry points: `main()` for the UI app, and `service_main()` for the service app.
- `main()` and `service_main()` are called by the UI app and service app respectively when they start.

The idea of sharing of Dart code between apps makes sense for me, although you guys might have different opinions.

In order to implement the design, we need several things to be done:

- [x] Custom entry point support in the embedder. → https://github.com/flutter-tizen/engine/pull/149
- [ ] Update the tool (C++ and C# embeddings) to support custom entry points. → I'll implement this soon.
- [x] Organize the `templates` directory structure. → https://github.com/flutter-tizen/flutter-tizen/pull/167
- [ ] Create a new template (`multi-app`) next to `ui-app` and `service-app`. The template should consist of two separate directories for UI app project and service app project. The service app's `runner` should be configured to pass `service_main` to the embedder as an entry point.
- [ ] Modify the `TizenProject` class (`tizen_project.dart`) to support the multi app structure.
- [ ] Modify the `NativeTpk` class (`tizen_build_target.dart`) to support building multi apps.
- [ ] (Optional) Also support the .NET app type.
- [ ] Implement an way to start the service app from the UI app. I'm not currently sure which is the best way to implement this.
- [ ] Document the usage with a code example (similarly to https://github.com/flutter-tizen/flutter-tizen/wiki/Creating-a-service-application). The Dart code example should look like:<p> 
  ```dart
  import 'package:flutter/material.dart';

  @pragma('vm:entry-point')
  void main() {
    runApp(MyApp());

    // <!-- Start the service app (somehow). -->
  }

  @pragma('vm:entry-point')
  void service_main() {
    // ...
  }
  ```
  The entry points may be placed in separate files (`main.dart` and `service_main.dart`), but it will require additional work in the tool.

Tip) You can debug the flutter-tizen tool without using many `print`s: https://github.com/flutter-tizen/flutter-tizen/wiki/Debugging-the-flutter%E2%80%91tizen-tool

**Comment by bwikbs** [comment]
After implementation of this is completed, I guess it will be possible to use it for multi-screen scenario. :smile: (https://github.com/flutter-tizen/engine/issues/94)
I think I could just focus on ``FlutterEngineGroup`` for optimization.

**Comment by pkosko** [comment]
@swift-kim Thanks for the tip about running flutter-tizen with debugger attached, it will be much more convenient.
Would you like me to take care of some steps from your TODO list? If so, which ones?

**Comment by swift-kim** [comment]
@pkosko Anything you want, if you want to contribute to the project. :)

Please beware that #171 and #167 are not merged to master yet.

**Comment by pkosko** [comment]
@swift-kim I've got a question to:

> Create a new template (multi-app) next to ui-app and service-app. The template should consist of two separate directories for UI app project and service app project. The service app's runner should be configured to pass service_main to the embedder as an entry point.

Do we assume that only single service can be added to application or we should support multiple services?

**Comment by swift-kim** [comment]
@pkosko AFAIK up to 3 or 4 service apps can be packaged into a single package but I don't think there's such a requirement or use case. I think we can basically assume at most one service app within a package.

cc @jkpu

**Comment by pkosko** [comment]
Ok, I will base on the assumption that only one service application is supported.

**Comment by pkosko** [comment]
I've managed to achieve the goal of this enhancement - application including a ui and service parts packed into single TPK file.
https://github.com/pkosko/flutter-tizen/tree/multipackage_add_template.

My code:
- supports cpp style multi-applications
- use a tizen/internal/app_control_method channel for starting a service (stoping currently doesn't work - needs further investigation)
- was tested for ui-only application and multi-applications:
  - creation and build
  - running application on the device
  - running application in debug mode
  - running an application which uses some dart plugin
all above seem to work as expected.

Starting a service from multi-application seem to work well, other process is launched.

Now I need to rebase the code to base on changes introduced with https://github.com/flutter-tizen/flutter-tizen/pull/181, after that I will make a PR.

**Comment by pkosko** [comment]
https://github.com/flutter-tizen/flutter-tizen/wiki/Application-types - multi app feature described on this page.
I think that we can close this issue.
