### ISSUE TITLE
How to add include and library files to rootstrap?

### ISSUE THREAD

**Issue by justwrite99** [flutter-tizen/flutter-tizen#157]
I added header files and libraries of vconf manually to the directory, `tizen-studio\platforms\tizen-4.0\wearable\rootstraps\wearable-4.0-device.core` .

Could you please add vconf header files and library to the rootstrap?

**Comment by swift-kim** [comment]
What is vconf? Is it a standalone library or is it pre-installed on your target device?

**Comment by justwrite99** [comment]
Vconf is one of IPC libraries given by tizen platform.

**Comment by bwikbs** [comment]
I guess you can update [here](https://github.com/flutter-tizen/tizen_tools/blob/master/sysroot/build-rootfs.py)

**Comment by swift-kim** [comment]
I can't find anything related to vconf in the public wearable API list. Are you trying to use an internal API which is not documented publicly? If so, neither we nor the Tizen SDK team supports such use case. One way to work around is to manually modify or replace the rootstrap installed on your machine (as you already did).

**Comment by justwrite99** [comment]
Vconf has been used since the beginning of tizen tv. 
I found out that vconf was replaced with buxton. However, vconf interfaces still remain.

**Comment by swift-kim** [comment]
No matter how the API is old, "undocumented" means that the API is not supported officially. You need to submit an API change request (ACR) to the SDK team if you want the API to be part of the Tizen SDK.

**Comment by justwrite99** [comment]
Where to find if a certain library is included in official Tizen SDK?

**Comment by swift-kim** [comment]
The most straightforward way is to find in the rootstrap directory itself, for example on Unix:

```sh
find ~/tizen-studio/platforms/tizen-4.0/wearable/rootstraps/wearable-4.0-device.core/lib -name *vconf*
```

Otherwise you can check whether the API you want to use is documented in [the Tizen API references](https://docs.tizen.org/application/native/api/wearable/latest). This way is not very accurate because a few internal APIs are accidentally documented in the public API references.

**Comment by bwikbs** [comment]
> This way is not very accurate because a few internal APIs are accidentally documented in the public API references.

:smile: 

@justwrite99  Just curious, what API are you going to use?

**Comment by justwrite99** [comment]
@bwikbs I'm going to use vconf library that has been used since the beginning of tizen tv.

**Comment by swift-kim** [comment]
You will be able to use this method: https://github.com/flutter-tizen/flutter-tizen/pull/164#issuecomment-883042731

after the PR is merged.

**Comment by swift-kim** [comment]
I think the question has been answered. Please feel free to reopen the issue if you want to resume the conversation.
