### ISSUE TITLE
Can't run gallery app in debug mode on TW3 using flutter-tizen run

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/flutter-tizen#16]
I have tested it on a mobile emulator, wearable emulator, tm1, and tw3. It only happened on tw3.
If you run it directly through the home screen, it runs normally.

- Environments
  - tw3 : tizen-6.0-unified_20201216.3
  - flutter-tizen : e02d726dc1f01576b1b4d3c91252737bfdc58680
  - gallery : 9565ba14177868a934d3415cfc4b07427dc1f67b

- How to reproduce 
  ``` bash
  flutter-tizen run 
  ```

- Detailed log
  - [logs.txt](https://github.com/flutter-tizen/flutter-tizen/files/5737899/logs.txt)

**Comment by swift-kim** [comment]
It seems the app process was killed due to insufficient memory left on the device. I was able to see this log message when trying to debug gallery app on SM-R800 (TW3):
```
E/RESOURCED( 2609): vmpressure-lowmem-handler.c: lowmem_kill_victim(580) > we killed, force(0), 7991 (Runner.dll) score = 300 (300), size: rss = 156784 KB, sigterm = 0
```
Because I can't turn on the device screen and can test only remotely, the app's oom (out of memory) score is 300 (which means background AFAIK). So the result may be different if I run the app in foreground and test again. I have some experience with resourced so I'll analyze in more detail when I'm back at office.

Could you check the `dlogutil RESOURCED` result on your device? You can use `flutter-tizen attach` instead of `flutter-tizen run` to skip build and install.

**Comment by bbrto21** [comment]
@swift-kim and I have seen that Resourced kill Runner.dll on tw3, 
We have to figure out if this is because the app has a huge resource or if the engine needs optimization.

**Comment by swift-kim** [comment]
```
bash-3.2# memps -v
     PID  S(CODE)  S(DATA)  P(CODE)  P(DATA)     PEAK      PSS       3D GEM(PSS) GEM(RSS)     SWAP  oom_score_adj    COMMAND
   27151    14016        4    88132   225052   355812   316486      232        0        0        0            300    /opt/usr/globalapps/io.flutter.demo.gallery/bin/Runner.dll
```
The PSS of the app process increases up to 320 MB during launch and eventually decreases to 180 MB on success (or killed).

**Comment by swift-kim** [comment]
According to /proc/pid/smaps when the app successfully launched on TW3, the heap portion (including [heap] and [anon]) of the app process which is mostly managed by the Dart runtime took up 85.7% of PSS:
```
io.flutter.demo.gallery
                   SCODE   SDATA   PCODE   PDATA     PSS    (%)  nSHARED  PRIVATE    CODE    DATA     RSS
Stack                  0       0       0      76      76    0.0        0       76       0      76      76
Heap                   0       0       0  208792  208792   85.7        0   208792       0  208792  208792
CoreCLR Native         0       0    3656     200    3856    1.6        0     3856    3656     200    3856
CoreFX  Native         0       0      68      12      80    0.0        0       80      68      12      80
CoreCLR Managed        0       0    1624    1152    2776    1.1        0     2776    1624    1152    2776
CoreFX  Managed        0       0      36     184     220    0.1        0      220      36     184     220
TizenFX Managed        0       0     120     152     272    0.1        0      272     120     152     272
System Native       7636       0    2536    1840    5494    2.3     1118     4376   10172    1840   12012
System Resource        0       0       0       0       0    0.0        0        0       0       0       0
Packages               0       0       8      32      40    0.0        0       40       8      32      40
App                    0       0       0       0       0    0.0        0        0       0       0       0
Others                 0       4   21640     348   21988    9.0        0    21988   21640     352   21992
Total               7636       4   29688  212788  243594  100.0     1118   242476   37324  212792  250116
```

The kernel snapshot (kernel_blob.bin) and the Flutter engine (libflutter_engine.so) took only 21 MB of the process memory:
```
io.flutter.demo.gallery
                   SCODE   SDATA   PCODE   PDATA     PSS    (%)  nSHARED  PRIVATE    CODE    DATA     RSS
Others                 0       4   21640     348   21988  100.0        0    21988   21640     352   21992
                       0       0   15140       0   15140   68.9        0    15140   15140       0   15140 /opt/usr/globalapps/io.flutter.demo.../kernel_blob.bin
                       0       0    6456     324    6780   30.8        0     6780    6456     324    6780 /opt/usr/globalapps/io.flutter.../libflutter_engine.so
                       0       0      44      20      64    0.3        0       64      44      20      64 /opt/usr/globalapps/io.flutter..../libflutter_tizen.so
```

At the same time Dart DevTools showed the heap size of 84.5 MB and the heap treemap looked like this:

![Screenshot from 2021-01-28 17-38-25](https://user-images.githubusercontent.com/40190588/106111927-feeb8e80-618f-11eb-8ede-7eed63097596.png)

**Comment by swift-kim** [comment]
There's no way to mitigate this problem right now. The gallery app running in debug mode consumes a similar amount of memory on Android. We'll revisit this problem when it's appropriate.

```
Gallery (debug) (x86 emulator)

 App Summary
                       Pss(KB)                        Rss(KB)
                        ------                         ------
           Java Heap:     6068                          19720
         Native Heap:    44088                          46068
                Code:    22056                         103876
               Stack:      640                            644
            Graphics:        0                              0
       Private Other:   191208
              System:     4292
             Unknown:                                  194512

           TOTAL PSS:   268352            TOTAL RSS:   364820
```
