### ISSUE TITLE
Is there any way to make partial window app?

### ISSUE THREAD

**Issue by justwrite99** [flutter-tizen/flutter-tizen#161]
It'd be better to look at the image below to understand what partial window apps are.

![ui](https://cdn1.expertreviews.co.uk/sites/expertreviews/files/samsung_tizen_tv_5.jpg)

Volume and channel indicators can be called "partial window apps" in tizen tv.
(or can be called full screen apps with full transparency. I'm fine with either ways.)
It'd be great if I can implement apps like above with flutter-tizen.

**Comment by xuelian-bai** [comment]
I think it's possible to set the window size to be as small as current volume app on Tizen TV, composition and key handler will be done by e20. But, for these kind of apps, what's the benefit can you get by using flutter? I mean the UX seems simple, but the logic is complicated.

**Comment by swift-kim** [comment]
Currently only "rectangular" non-transparent apps can be created with flutter-tizen, even with the [recent patch](https://github.com/flutter-tizen/engine/pull/133) made to the engine.

By the way how can you manage the focus when multiple apps are displayed in one screen? When does an app gets a focus or loses it?

**Comment by xuelian-bai** [comment]
transparency is not a problem, it could be supported. 
Focus management is done by e20, e20 will check location of window and set focus to coresponding window. 
For volume app, there is a daemon service, it will handle volume key and display the coresponding icon, most common scenario is, it display an icon on top of tv-viewer, and tv-viewer is actually displaying video on video plane, it's not a complicated scenario for e20.

**Comment by justwrite99** [comment]
@xuelian-bai I'm maintaining legacy code written in c w/ Efl which is really horrible. I'd like to re-implement them with flutter if possible. So I'm just trying to give it a shot. 

Could you please give me some example code?

**Comment by xuelian-bai** [comment]
right now, you can first setup flutter-tizen environment https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/get-started.md, when you run flutter-tizen create you will get a example code, you can create your widget based on it. right now, you can work on full screen first.

**Comment by xuelian-bai** [comment]
https://github.com/flutter/samples these are official samples

**Comment by swift-kim** [comment]
It seems not possible to display an app on top of another app. When I open a full screen app (A) and try to open a partial app (B) on TV emulator, the app A is closed and only the app B is displayed:

![image](https://user-images.githubusercontent.com/40190588/125012412-1adf4e80-e0a5-11eb-80ea-2f3de32d1cea.png)

If this is just what you want for now, you can try by applying [this PR](https://github.com/flutter-tizen/flutter-tizen/pull/159) which hasn't been merged yet.

1. Go to the flutter-tizen installation directory and fetch the PR. For example,

   ```sh
   git config --global alias.pr '!f() { git fetch -fu ${2:-$(git remote |grep ^upstream || echo origin)} refs/pull/$1/head:pr/$1 && git checkout pr/$1; }; f'
   gir pr 159
   ```

1. Remove or invalidate existing engine artifacts (if exist).

   ```sh
   rm flutter/bin/cache/tizen-sdk.stamp
   ```

1. Download the build output of https://github.com/flutter-tizen/engine/pull/133 directly from the CI server.

   ```sh
   AZURE_BUILD_ID=368 flutter-tizen precache --tizen
   ```

1. Change the app's `tizen/App.cs` file as follows:

   ```csharp
   using System.Drawing;
   using Tizen.Flutter.Embedding;

   namespace Runner
   {
       public class App : FlutterApplication
       {
           protected override void OnCreate()
           {
               WindowOffset = new Point(0, 300);
               WindowSize = new Size(320, 480);

               base.OnCreate();
               ...
   ```

1. Run the app.

**Comment by xuelian-bai** [comment]
normally two apps will act just like you said, but as I know, tv-viewer is a special app on tv.

**Comment by justwrite99** [comment]
@xuelian-bai 
I've experienced in android app development with flutter already. I just wanted to keep the same experience and fun on tizen tv.
And now I'm maintaining tvviewer app and trying to make a chance to apply flutter. Which I guess make other people see some benefits on using flutter. 

And tvviewer is not a special app. It is as same as other apps. There is nothing special about it.
BTW, It is wonderful that you knew tvviewer.

How could I implement the replica of tvviewer with flutter? 
Especially, channel and volume indicators.

1st obstacle is partial window app.

**Comment by xuelian-bai** [comment]
for partial window app, 
1. as @swift-kim mentioned, he has a patch #159  for creating small window, when it merged, you can create a small window 
2. To make it as a partial window, we still need to set window transparency and background transparency inside flutter-tizen engine, we will support it soon.

**Comment by swift-kim** [comment]
I made a patch (https://github.com/flutter-tizen/engine/pull/139) as suggested by @xuelian-bai.

![image](https://user-images.githubusercontent.com/40190588/125214513-8f5afd00-e2f2-11eb-95d8-856f4efd06fe.png)

In order to create an app which has a transparent background,

1. Apply https://github.com/flutter-tizen/flutter-tizen/issues/161#issuecomment-876863935 with `AZURE_BUILD_ID=383`,
2. Change your app's `main.dart` as follows:<p>
   ```dart
   ...
   return Scaffold(
     backgroundColor: Colors.transparent,
     appBar: AppBar(
       ...
   ```

Note that the partial window app still gets the main focus while it's running. I tried to set `ecore_wl2_window_type_set` to something else than `ECORE_WL2_WINDOW_TYPE_TOPLEVEL` but it didn't help.

**Comment by xuelian-bai** [comment]
elm_win_prop_focus_skip_set(Evas_Object *obj, Eina_Bool skip) can be set to skip focus for the window, but seems that we can't use it...

**Comment by swift-kim** [comment]
@xuelian-bai It worked and I created a property `focusable` in https://github.com/flutter-tizen/engine/pull/139. Please take a look.

@justwrite99 Is this actually what you need?

**Comment by justwrite99** [comment]
@swift-kim Thank you for your efforts. I guess this is it!! 👍
