### ISSUE TITLE
Drive command doesn't cache engine artifacts

### ISSUE THREAD

**Issue by HakkyuKim** [flutter-tizen/flutter-tizen#169]
`flutter-tizen drive` command doesn't cache engine artifacts.

Steps to reproduce:

1. delete `flutter/bin/cache/artifacts/engine`
2. go to one of the example app that has integration test files in our Tizen plugin repo.
3. run integration test using the drive command

```sh
flutter-tizen drive --driver=<some driver> --target=<some target>
...
FileSystemException: Directory listing failed, path =                   
'/home/hakkyu/mydir/project/flutter_tizen_dev/flutter_tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/' (OS Error: No such file or directory, errno
= 2)
...
```

Overriding `requiredArtifacts` for `TizenDriveCommand` solves the issue:

```dart
@override
Future<Set<DevelopmentArtifact>> get requiredArtifacts async =>
    <DevelopmentArtifact>{
    DevelopmentArtifact.androidGenSnapshot,
    TizenDevelopmentArtifact.tizen,
    };
```

Every command that uses the engine artifacts will also need the same patch.

@WonyoungChoi 
Could you take a look?

**Comment by WonyoungChoi** [comment]
@HakkyuKim It would be better to override the `requiredArtifacts` only if necessary such like `build` and `run`. If `drive` command needs the artifacts, it should be added.

**Comment by swift-kim** [comment]
The drive command is pretty much similar to the run command, so if any change is made to `run.dart`, the same change should be made in `drive.dart`. If you want to avoid code duplication, you can create a mixin that overrides the `requiredArtifacts` property of a `FlutterCommand`.

**Comment by HakkyuKim** [comment]
There are also other commands besides `drive` that require engine artifacts such as `test` and `install`. But running `build` or `run` before `drive`, `test`, or `install` may not always be the case. For a CI system, it will probably run `drive` or `test` first. Running `precache` before other commands works, but in my opinion, it creates a needless step.

The original Flutter command automatically updates the artifacts for all the above mentioned commands: 
- https://github.com/flutter/flutter/blob/5acf7e98f16222610a4e6bfe1e36b08a90cf53a4/packages/flutter_tools/lib/src/commands/test.dart#L62
- https://github.com/flutter/flutter/blob/5acf7e98f16222610a4e6bfe1e36b08a90cf53a4/packages/flutter_tools/lib/src/commands/install.dart#L15
- https://github.com/flutter/flutter/blob/5acf7e98f16222610a4e6bfe1e36b08a90cf53a4/packages/flutter_tools/lib/src/commands/run.dart#L32

`DeviceBasedDevelopmentArtifacts` creates required artifacts so that `verifyThenRunCommand` can update engine cache.

**Comment by WonyoungChoi** [comment]
I see, `run`, `drive`, `test` need the engine artifacts because they try to build the `tpk` if it is not built.  However the `install` is not available in that case. I will make a `Mixin` and apply it to `build`, `run`, `drive`, `test` first.
