### ISSUE TITLE
Locale priority issue

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#184]
Suppose that
- There is an app which supports only two locales, **de_DE** and **en_US**.
- I have a device whose default locale has been set to **ko_KR**.

When I run this app on this device, the app's locale automatically falls back to **de_DE**, because **ko_KR** is not supported by the app and **de_DE** comes first in the engine's preferred locale list (as Tizen's i18n module resolves available locales alphabetically).

- Should the engine resolve **en_US** first in this situation, just because it's more "natural" for general users?
- Is there a way to list available locales in an order of preference?
- How do other platforms or native/.NET apps deal with this situation?

**Comment by bwikbs** [comment]
> Should the engine resolve en_US first in this situation, just because it's more "natural" for general users?

I like this solution. Because there is no priority of locales except for the locale that is set in tizen.
It is not strange that  we choose ``en`` first.

**Comment by swift-kim** [comment]
I'll prepare a patch for this issue. I think we should only pass **ko_KR** to the engine but not the whole list of 730 languages.

**Comment by bwikbs** [comment]
>I'll prepare a patch for this issue. I think we should only pass ko_KR to the engine but not the whole list of 730 languages.

I'm not sure.. but I think it's a good solution. :+1:

**Comment by swift-kim** [comment]
https://flutter.dev/docs/development/accessibility-and-localization/internationalization

Internationalized apps can specify their supported languages using the `supportedLocales` parameter, and usually `en` (English) comes first in the list. Thus the solution will work exactly as you expect.
