### ISSUE TITLE
Document how to debug apps with VS Code

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#190]
https://github.com/sony/flutter-elinux/wiki/Debugging-with-VSCode

cc @xuelian-bai Did you know this? This is cool!

**Comment by swift-kim** [comment]
I'm planning to let the tool automatically configure `launch.json` on app launch so that the user doesn't have to copy and paste `observatoryUri` manually. In that way, the user can just press the Run button (F5) to attach to a running app and start debugging. I'll prepare a PR soon.

cc @xuelian-bai

**Comment by xuelian-bai** [comment]
That sounds good. 
I have one concern, in vscode, for example, run a java application, user can set breakpoint and run, user don't need to attach a running app manually, in this way, user can debug an app which may can't launch properly, but, if app can only be attached, the precondition is that the app can launch properly.
But, it seems that this method use offcial vscode flutter extension, which is not open source, I think maybe we have no other way to debug...

**Comment by swift-kim** [comment]
@xuelian-bai Yes, I'm aware of that limitation. Only the "Attach and Debug" function can be supported in the way I mentioned. I'll try to find a way to enable "Run and Debug", but actually there could be no way to resolve the limitation. Still, I think the limitation is something that can be understanded by users as long as we document it properly.

> the precondition is that the app can launch properly.

FYI, there is an option `--start-paused` that can provided to the `flutter-tizen run` command. Code execution can be paused until a debugger is attached.

> offcial vscode flutter extension, which is not open source,

Why do you think it's not open-sourced: https://github.com/Dart-Code/Dart-Code :)

There's a chance to contribute to the project, as I mentioned as a second option in https://github.com/flutter-tizen/flutter-tizen/issues/88#issuecomment-823812365.
