### ISSUE TITLE
Memory leak in runner.cc file

### ISSUE THREAD

**Issue by wb0716** [flutter-tizen/flutter-tizen#206]
please check this file:
https://github.com/flutter-tizen/flutter-tizen/blob/master/templates/ui-app/cpp/src/runner.cc

int main(int argc, char *argv[]) {
  auto app = new App();
  return app->Run(argc, argv);
}

there is new a memory, but no delete.  memory leak.
so can change it like this:
int main(int argc, char *argv[]) {
  App app;
  return app.Run(argc, argv);
}

**Comment by swift-kim** [comment]
Good point! Could anybody prepare a fix?

**Comment by xiaowei-guan** [comment]
> Good point! Could anybody prepare a fix?

Ok, I will fix it.

**Comment by xiaowei-guan** [comment]
#209
