### ISSUE TITLE
Add test code

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#223]
I previously tried to add some unit tests for our tool code but gave up soon because the code was not mature enough then and it was obviously not worth taking the efforts. Now I'd like to add some hermetic/permeable tests at least for some commands like `create` and `build` that are easy to break.

**Comment by HakkyuKim** [comment]
I'd like solve this if no one has started yet. 

@swift-kim 
Are you thinking of implementing `build_apk_test.dart` and `create_test.dart` for Tizen projects?

**Comment by swift-kim** [comment]
@HakkyuKim Generally, yes. The unit of testing target could be either function (unit testing - `general.shard`) or command (`commands.shard`).

The important principle I have in my mind is that we need to test only "real" things that are meaningful for us. Testing trivial scenarios or just increasing the test coverage of the code is not my goal. I don't plan to "copy" tests from flutter_tools (although you can refer to how they work), and I want to test only Tizen-specific things that are not tested by the original flutter_tools.

I had some specific test cases that I wanted to test, and I'll list them up (or implement) later. We need to set up the testing environment first. When I tried last time I needed to copy the entire `test` directory from flutter_tools and make [this change](https://github.com/swift-kim/flutter-tizen/commit/f25aa797383565ff72f812869932f627d1846d70#diff-06d52610e4161af0c5f25ee28845eee6e809585eb8cee475dc7b3d68b9345d96). It would be better if there's another way that doesn't require copying the directory.

**Comment by HakkyuKim** [comment]
@swift-kim 
I see, currently I can think of service app and multi-app for Tizen specific tests, I'm sure there are more. It would be helpful to have some scenarios to start with.

Regarding the testing environment, I can't figure out the best way to depend on `test/src` because I'm unsure about the factors involved. Is the most concerning part resolving future changes to the `test/src` directory?

Currently I see two options:
- As you mentioned, copying the `test/src` directory and make changes for flutter-tizen, or
- Creating single file `test/tizen_common.dart` export all modules in `test/src` but hide the ones that we need to implement for flutter-tizen.

This is another question, is there anything I should be aware of if I use the import statement, `import ../../flutter/packages/flutter_tools/test/src/context.dart;` from say `test/tizen_create_test.dart`?

**Comment by swift-kim** [comment]
@HakkyuKim If I were you, I would start with adding tests for code authored by myself (because the author knows the code best). Otherwise, bugs fixed by previous PRs would be good candidates for adding tests. For example, we may add a test case for https://github.com/flutter-tizen/flutter-tizen/pull/225 to check that running `flutter-tizen create` for an existing project directory doesn't overwrite its `lib/main.dart`.

> Regarding the testing environment, I can't figure out the best way to depend on `test/src` because I'm unsure about the factors involved.

Previously there was a problem with setting `Cache.flutterRoot` for the test runner. No test could be run without modifying the `testUsingContext` function for that reason. I need to check this again.

> Is the most concerning part resolving future changes to the `test/src` directory?

Yeah, maybe. I just thought it would be better to avoid unnecessary duplication of code.

> This is another question, is there anything I should be aware of if I use the import statement, `import ../../flutter/packages/flutter_tools/test/src/context.dart;` from say `test/tizen_create_test.dart`?

No, I don't think so. Using the relative path is inevitable and makes sense for me.

**Comment by swift-kim** [comment]
How about adding a bunch of one-line files that only contain the `export` directive, to avoid long relative path resolution in test files?

e.g. `test/src/common.dart` will contain only

```dart
export '../../flutter/packages/flutter_tools/test/src/common.dart';
```

Some files may be extended for Tizen if necessary (as you suggested in the above).

e.g. `test/src/context.dart` will look like

```dart
import 'dart:async';
...
import 'throwing_pub.dart';

export '../../flutter/packages/flutter_tools/test/src/context.dart'
    hide testUsingContext;

@isTest
void testUsingContext(
  ...
}
```

**Comment by swift-kim** [comment]
> Previously there was a problem with setting `Cache.flutterRoot` for the test runner. No test could be run without modifying the `testUsingContext` function for that reason. I need to check this again.

As far as I can see this problem is still present.

**Comment by HakkyuKim** [comment]
Your suggestion sounds good. We can preserve the file structure of `test/src/*` without duplication and extend modules for Tizen.

> As far as I can see this problem is still present.

Could you share link to the code that produced this error? I'm currently not sure why but [this code](https://github.com/HakkyuKim/flutter-tizen/blob/test-environment/test/commands_test.dart) works on my machine so I want to compare the differences. I originally had FLUTTER_ROOT set but it kept working even after unsetting the environment variable.

**Comment by swift-kim** [comment]
@HakkyuKim The error is generated at line 67 of `test/src/common.dart` as you can see in the above stack trace.

The error can be worked around by setting an environment variable so it shouldn't much matter. This just worked:
```
FLUTTER_ROOT=flutter flutter-tizen test test/commands_test.dart
```

**Comment by HakkyuKim** [comment]
@swift-kim 
Yeah, just realized `test/src/common.dart` was still reading the environment variable `FLUTTER_ROOT` from my system even after I've unset it. `echo $FLUTTER_ROOT` shows nothing but I can see the `FLUTTER_ROOT` entry when I print `Platform.environment` in dart. Not sure why.

Anyways, setting the environment variable in the command line, or setting `Cache.flutterRoot` in the `setUp` function will solve the issue.

**Comment by HakkyuKim** [comment]
@swift-kim 
Now I understand that there's no way to avoid the error at line 67 of `test/src/common.dart` other than setting `FLUTTER_ROOT`. If this is okay with you, I can send a PR request that includes some essential files for writing tests:
https://github.com/HakkyuKim/flutter-tizen/tree/test-environment/test.

**Comment by swift-kim** [comment]
@HakkyuKim Sure. Thanks.
