### ISSUE TITLE
SelectableText doesn't display ToolbarOptions

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#240]
Unlike on Android, `toolbarOptions` for `SelectableText` have no effect on Tizen. On Android, the **Copy** and **Select All** buttons are automatically displayed when the user interacts with `SelectableText`.

<img src="https://user-images.githubusercontent.com/40190588/135449118-4b6a5fed-2d2c-4cc7-9200-7b84ec806af4.png" width="360"/>

To implement a similar thing on Tizen, the app developer should manually create a button like this:

```dart
Column(
  mainAxisAlignment: MainAxisAlignment.center,
  children: <Widget>[
    SelectableText(
      text,
      showCursor: true,
      toolbarOptions: const ToolbarOptions(copy: true, selectAll: true), // NO EFFECT!
      onSelectionChanged: (
        TextSelection selection,
        SelectionChangedCause? cause,
      ) {
        _selectedText = selection.textInside(text);
      },
    ),
    ElevatedButton(
      onPressed: () async {
        await Clipboard.setData(ClipboardData(text: _selectedText));
        print('Copied: $_selectedText');
      },
      child: const Text('Copy'),
    ),
  ],
)
```

<img src="https://user-images.githubusercontent.com/40190588/135446048-d8cc2174-26ec-4ce7-9936-1bdd63caa849.png" width="260"/>

**Comment by bwikbs** [comment]
Is this our bug? And how did you find ``button`` solution? :+1:

**Comment by swift-kim** [comment]
@bwikbs I don't know how the toolbar is displayed on Android or iOS so I can't tell where the bug arises. Maybe the Tizen platform doesn't natively support such toolbar.

The button is just a plain button. It isn't really a practical solution. :(

**Comment by swift-kim** [comment]
The toolbar is drawn by the Flutter framework but not by the platform. Tizen's `TargetPlatform` is Linux, so the framework follows the Linux desktop's Material design convention (that is, no text selection handle).

https://github.com/flutter/flutter/blob/2.10.1/packages/flutter/lib/src/material/selectable_text.dart#L649

https://github.com/flutter/flutter/blob/2.10.1/packages/flutter/lib/src/material/desktop_text_selection.dart#L57

If you modify the framework code a bit (replace `desktopTextSelectionControls` with `materialTextSelectionControls`), the toolbar will appear just as seen on Android. Also the "Copy" and "Select All" buttons work perfectly.

<img src="https://user-images.githubusercontent.com/40190588/166185319-02cfcce2-4938-43bc-9c3e-b00ac1faa5d4.png" width="260">

However, I couldn't see the "Cut" and "Paste" buttons when working with TextFields. Let me check on another device when I'm back to the office.

<img src="https://user-images.githubusercontent.com/40190588/166185734-a8be6933-c450-4c1d-8bcd-e8041cdde170.png" width="260">

**Comment by swift-kim** [comment]
Currently we cannot make Tizen-specific modifications to the Flutter framework, so the change in the above comment will not be applied by default.

We'll implement this feature if there's a demand from our users. Please leave a comment here if you are the one who wants it.
