### ISSUE TITLE
Conditional Import for Tizen

### ISSUE THREAD

**Issue by callwait** [flutter-tizen/flutter-tizen#241]
Hi there, I'm looking for something similar:
```
import 'tizen_stub.dart'
    if (dart.library.tizen) 'tizen.dart'
```

How can I specify conditional imports for Tizen?

**Comment by swift-kim** [comment]
Dart doesn't seem to allow that, according to https://github.com/dart-lang/sdk/issues/34262#issuecomment-416129832. The same applies to other platforms like Android and Windows (there's no such directive as `dart.library.android`). There's no way for the compiler to know on which platform the compiled code will run in advance.

Side note) If you want to check the currently running platform **at runtime**, the [current best practice](https://github.com/flutter-tizen/flutter-tizen/wiki/Limitations#unsupported-features) is to use
```dart
bool isTizen = Platform.environment.containsKey('TIZEN_API_VERSION')
```
which is the Tizen equivalent of `Platform.isAndroid`, `Platform.isWindows`, ...
