### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#254]
Apple Silicon (M1) Macs are currently not supported by flutter-tizen just because its dependent tooling (Tizen Studio) doesn't still support Apple Silicon-based devices.

The flutter-tizen tool itself is fully compatible with Apple Silicons and can be used to build Tizen apps as long as Tizen Studio is installed properly on the host machine. Currently there's an issue with installing Tizen Studio (GUI version) on Apple Silicon-based devices but I was able to work around on my M1 Macbook using [this method](https://forum.developer.samsung.com/t/tizen-studio-and-mac-os-issues/9279/9). There will be no issue if you just want to use the CLI version of Tizen Studio.

Note that you can't use Tizen emulators even if you manage to install Tizen Studio. You can only use real devices connected via sdb.

I will update https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/macos-install.md once the next version of Tizen Studio with Apple Silicon support is officially released.

**Comment by swift-kim** [comment]
Tizen Studio 4.5 has finally been released but it seems it's still not compatible with macOS Big Sur/Monterey and M1 Macs.

I at least managed to install Tizen Studio itself but ended up with seeing the following error when trying to open the IDE or Certificate Manager.

> The JVM shared library "/Users/swift/tizen-studio/jdk/Contents/Home/bin/../jre/lib/server/libjvm.dylib"
does not contain the JNI_CreateJavaVM symbol.

<img width="372" src="https://user-images.githubusercontent.com/40190588/140651529-f40ccd80-5b49-4161-9f12-112329e4635b.png">

There's still no problem with building Flutter apps using the flutter-tizen tool if you don't need any GUI tools (i.e. you can create your own security profile from the command line), but anyway it's hard to say Tizen Studio is officially supported on the latest versions of macOS and Apple Silicon-based devices.

**Comment by swift-kim** [comment]
It isn't likely Apple Silicons will be officially supported by the Tizen Studio team in the near future. (What a shame!)

I'll close this issue for now.

**Comment by deandreamatias** [comment]
Hi @swift-kim 
I think that need reopen this issue because it's a significant obstacle for developers
