### ISSUE TITLE
Problems with the order of libs used by plugin build

### ISSUE THREAD

**Issue by bwikbs** [flutter-tizen/flutter-tizen#277]
In the following PR, message-loop lib used by lwe was added.
https://github.com/flutter-tizen/plugins/pull/246

And especially when building arm, I get the following error.
https://github.com/flutter-tizen/plugins/runs/4186671585?check_suite_focus=true

I'm guessing this is a matter of the ordering of the libraries used when  linking.

And.. this is workaround for better understanding
[lib/build_targets/plugins.dart](https://github.com/bwikbs/flutter-tizen/commit/f32bade87f17d102ebcece62b2c85a18852ebccc)

**Comment by swift-kim** [comment]
We might need to give the `-pthread` option to the native compiler.

**Comment by swift-kim** [comment]
Oh, the `-lpthread` option is already present in the build command (provided by Tizen SDK's `makefile.mk`), and it really looks like a matter of linking order as you said.

**Comment by bwikbs** [comment]
You're right. And for now, I don't have any idea except workaround. Any suggestion?

**Comment by swift-kim** [comment]
Here is my fix which is not very different from your solution: https://github.com/flutter-tizen/flutter-tizen/pull/278

**Comment by bwikbs** [comment]
Wow! It's very fast :+1: 
Of course I love it!. My only concern is  you!! :smile:
