### ISSUE TITLE
Flutter performance

### ISSUE THREAD

**Issue by patrykka** [flutter-tizen/flutter-tizen#282]
Hi All,

Something strange happen, few weeks ago I was testing flutter application on performance (avg FPS counter from DevTools performance).
Currently application is working very slow with low avg FPS while few weeks ago It was much faster. Anyone is dealing with similar problem?

My test app is just 1000 elements scrollable ListView with text as items + button to trigger scroll to end.

**Comment by swift-kim** [comment]
Are you running the app in profile mode? A warning message will be displayed if you try to analyze performance in debug mode.

**Comment by patrykka** [comment]
Profile mode is not working on tizen same as release mode.

**Comment by swift-kim** [comment]
Hmm? Why doesn't it work?

https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/commands.md#run

**Comment by patrykka** [comment]
@swift-kim you are right, I am sorry for confusion. 
I mixed those two things.
