### ISSUE TITLE
Can plugin specify required version of flutter-tizen (sdk)?

### ISSUE THREAD

**Issue by wiertel** [flutter-tizen/flutter-tizen#283]
Is it possible for a plugin (not sure it would be useful for apps) to declare a version of flutter-tizen/flutter-tizen sdk/engine that it requires/is compatible with?

After a change in engine (flutter-tizen/engine#209) the webview_flutter_tizen has applied it (flutter-tizen/plugins#278). And then, when I tried to build an application with updated plugin I got a C++ compilation error. That was fixed by updating flutter-tizen. The build break in application is justified and understandable. But it would be a lot nicer if there was short error, possibly with helpful information.
I guess that for showing something like this before trying to build the app would need the plugin to declare dependency/require/compatible version of flutter-tizen.

**Comment by swift-kim** [comment]
Yeah, it's a known issue, and unfortunately there's no way to define a compatible flutter-tizen version inside a plugin (only Dart and Flutter versions can be specified), because the flutter-tizen tool and engine are even not "versioned" linearly. (We currently manage [released engine](https://github.com/flutter-tizen/engine/releases) versions only using hash values.) The current best practice is not to make such a breaking API change between the embedder and plugins, and if it is made, notify the users of the plugins to use the latest available flutter-tizen tool.

Does anybody have a good idea to deal with this issue?

**Comment by wiertel** [comment]
It makes sense to manage the changes as you described for now. Maybe it is not even worth implementing anything else for that, as breaking changes would not be often. Or maybe could be coupled with main flutter sdk updates, so existing mechanism could be used.
By existing mechanism I mean [SDK constraints](https://dart.dev/tools/pub/pubspec#sdk-constraints).
Ideas:
1. The fact that engine is not versioned is a major obstacle. Maybe build number could be used? Those are sequential and one can compare any 2 of them.
2. Contacting dart maintainers to discuss extending those SDK constraints with tizen engine information. They could either apply it, or suggest other way. We cannot simply add something to  `environment` as the structure is verified and it is processed by `pub get` etc - so outside of our reach.
3. Introduce a "virtual package" - either really virtual that the flutter-tizen would detect and react specially, or a real package with only purpose is to check current engine and fail if there is something wrong. The failure should result in nice error message or else there would be no benefit of the package.implement 
4. Something completely different - allow a plugin to specify custom message if build fails. Could be a global key in pubspec.yaml like "message_if_build_fails" or "failed_build_notice" that will be shown (with a frame) if the flutter-tizen detects that a plugin build has failed. I've checked that extra keys in pubspec are simply ignored, but I'm not sure if it would affect some static analysis that is done on packages by pub.dev

Feel free to close this issue, as I admit this might not be really important feature.

**Comment by swift-kim** [comment]
Another solution is to merge the plugin implementation into the embedder itself and manage together. The approach is used by some other embedders such as [flutter-pi](https://github.com/ardera/flutter-pi/tree/master/src/plugins) and [ivi-homescreen](https://github.com/toyota-connected/ivi-homescreen/tree/main/shell/static_plugins).

**Comment by wiertel** [comment]
New idea: pass information about engine/sdk used to the native compiler as defines (through command line or header). That way plugin would be responsible for reporting error early and could even ensure compatibility utilizing conditionals. Weather to use a version/build/compatibility flags or combination of those (e.g. one with major version and special flags introduced when need arises between major version changes). That would work for C++.
And I've now realized that there might be some C++ preprocessor magic to test for method existence. So maybe a plugin code could handle various versions some hacky way without any changes in flutter-tizen :)

**Comment by bwikbs** [comment]
> New idea: pass information about engine/sdk used to the native compiler as defines (through command line or header).

Can you give me a simple example? I don't quite understand what you're trying to do.

**Comment by wiertel** [comment]
> > New idea: pass information about engine/sdk used to the native compiler as defines (through command line or header).
> 
> Can you give me a simple example? I don't quite understand what you're trying to do.

Oh. That description might have been a little convoluted. I meant any way that plugin code could include conditionals like this:
``` cpp
#if ENGINE_BUILD > 150
#if FLUTTER_TIZEN_VERSION > 20503
#ifdef FLUTTER_TIZEN_HAS_GETWINDOW
```

**Comment by bwikbs** [comment]
> Oh. That description might have been a little convoluted. I meant any way that plugin code could include conditionals like this:

Got it. Thanks for the detailed explanation !!
