### ISSUE TITLE
Can't I build the flutter app in both tizen and windows?

### ISSUE THREAD

**Issue by sooinkang** [flutter-tizen/flutter-tizen#308]
Hello, 
I want to build a fluuter app in both tizen and windows.
before flutter-tizen setting, this project was built well in Windows.
after flutter-tizen setting, it appears as follows and is not built in Windows.

_Connecting to the VM Service is taking longer than expected...
Still attempting to connect to the VM Service...
If you do NOT see the Flutter application running, it might have crashed. The device logs (e.g. from adb or XCode) might have more details.
If you do see the Flutter application running on the device, try re-running with --host-vmservice-port to use a specific port known to be available._

So when I ran the **flutter run -d windows** command, the following error occurred.

_$ flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
lib/main.dart(5,8): error GBB7C8005: Error when reading '../flutter-tizen/flutter/packages/flutter/lib/material.dart'_

how can i solve this problem?

**Comment by swift-kim** [comment]
flutter-tizen doesn't affect your existing Flutter installation in any way.

Are you using WSL or something? Would you run `flutter clean` & `flutter pub get`?

**Comment by swift-kim** [comment]
I assume your problem has been resolved. Please reopen if you still need help.
