### ISSUE TITLE
TV Remote keys handling

### ISSUE THREAD

**Issue by AliaksandrTuzik** [flutter-tizen/flutter-tizen#319]
I have created a default flutter-tizen app and trying to handle Samsung Smart Remote keys
<img width="169" alt="Screenshot 2022-01-17 at 11 48 23" src="https://user-images.githubusercontent.com/38353540/149737340-7a3dc73c-9c25-4227-a57b-bc8a995e03bb.png">

When pressing Play/Pause button, a message "Not Available" 

![image](https://user-images.githubusercontent.com/38353540/149738429-3c13d657-0f48-4141-aa17-3a2621cbf914.png)

appears on the screen (seems to be a system message) which I have no idea how to get rid of

I've been trying to handle remote control keys with KeyboardListener
On Play/Pause button I get
`KeyDownEvent#b7d87(physicalKey: PhysicalKeyboardKey#c0075(usbHidUsage: "0x000c0075", debugName: "Brightness Auto"), logicalKey: LogicalKeyboardKey#00000(keyId: "0x1500000000", keyLabel: "", debugName: "Key with ID 0x01500000000"), character: null, timeStamp: 1:25:32.198076)
`
where it recognises the physical key as a "Brightness Auto" key - which does not look like Play/Pause I expect to get
And the logical key is just a dummy generated by flutter

What is the right way to handle the RC keys, in particular - Play/Pause button?
Can I rely on physical key ID (0x000c0075) or is there a better solution?
How do I get rid of this message appearing on Play/Pause button pressed?

**Comment by swift-kim** [comment]
Our current embedder implementation ([`key_event_channel.cc`](https://github.com/flutter-tizen/engine/blob/flutter-2.8.1-tizen/shell/platform/tizen/channels/key_event_channel.cc)) only provides XKB to GTK key mapping but TV remote controls seem to define their own internal key codes for special keys like play/pause. We need to carefully check how we should handle this.

**Comment by AliaksandrTuzik** [comment]
@swift-kim I would like to use flutter-tizen to implement some functionality tied to Play/Pause button on TV remote.
Is there any way I can contribute to the codebase to help cover this key mapping? Maybe you could provide me with the places in the code where I could look at, so that I can create a pull request with the changes needed to make this work?

**Comment by swift-kim** [comment]
The things are not that clear at the moment (at least for me). I need to verify several things - this issue could be even related to https://github.com/flutter-tizen/engine/issues/221 which will require a considerable amount of change to the embedder codebase. I'll check with a real TV device when I'm back at the office tomorrow.

**Comment by swift-kim** [comment]
I found an EFL documentation regarding the "Not Available" popup: https://docs.tizen.org/application/native/guides/ui/efl/key-grab

So the solution is quite straightforward. Calling `eext_win_keygrab_set(win, "XF86PlayBack")` during initialization of [`KeyEventHandler`](https://github.com/flutter-tizen/engine/blob/flutter-2.8.1-tizen/shell/platform/tizen/key_event_handler.cc) will get rid of the popup. (The ecore_wl2 equivalent of `eext_win_keygrab_set` is `ecore_wl2_window_keygrab_set`.)

However I think the overall key event handling logic in our embedder needs some refactoring. I'll open a PR and reference this issue when the work is done. You can rely on the physical key ID for now. I'll try to map it to `LogicalKeyboardKey.mediaPlayPause` in the future.

**Comment by AliaksandrTuzik** [comment]
> So the solution is quite straightforward. Calling `eext_win_keygrab_set(win, "XF86PlayBack")` during initialization of [`KeyEventHandler`](https://github.com/flutter-tizen/engine/blob/flutter-2.8.1-tizen/shell/platform/tizen/key_event_handler.cc) will get rid of the popup. (The ecore_wl2 equivalent of `eext_win_keygrab_set` is `ecore_wl2_window_keygrab_set`.)

So, it is not possible to fix the message by Flutter/Dart means only - hence, I need to wait for the PR to be merged?

**Comment by swift-kim** [comment]
@AliaksandrTuzik Yes, it could take up to 2-3 weeks. If this is urgent for you, I can make a [quick fix](https://github.com/swift-kim/engine/commit/7276fd49f35d4e068b5493e476f5ac9f73ef371e) with minimal changes.

**Comment by AliaksandrTuzik** [comment]
> @AliaksandrTuzik Yes, it could take up to 2-3 weeks. If this is urgent for you, I can make a [quick fix](https://github.com/swift-kim/engine/commit/7276fd49f35d4e068b5493e476f5ac9f73ef371e) with minimal changes.

That would be great if you did that
Thanks in advance!

**Comment by swift-kim** [comment]
I created a PR with the quick fix: https://github.com/flutter-tizen/engine/pull/232

You can test the change before it's merged as long as you have GitHub CLI installed on your host (see the PR comment). After testing, you can switch back to the original embedder by running `flutter-tizen precache --tizen --force`.

**Comment by swift-kim** [comment]
Will be fixed by https://github.com/flutter-tizen/engine/pull/234!

**Comment by swift-kim** [comment]
To opt in to Flutter 2.8, run the following in the flutter-tizen installation directory:

```sh
$ git fetch origin
$ git checkout 2.8.1
```

**Comment by bbrto21** [comment]
> Caution: The physical key code for the play/pause button will be changed to 0x000c00cd (`PhysicalKeyboardKey.mediaPlayPause`). Currently there's no logical mapping for this key in the framework ([`kGtkToLogicalKey`](https://github.com/flutter/flutter/blob/ba01ec8faae9a9be3cd90ee2b7357a803b7a7178/packages/flutter/lib/src/services/keyboard_maps.dart#L1716)).

@swift-kim 
Could you add a guide for handling TV remote control?
For application developers who want to write for some app for TV, It would be nice if there was a guide of how flutter-tizen maps the physical keys of the remote control and provides them.

**Comment by swift-kim** [comment]
@bbrto21 The TV input system is fundamentally broken and the remote control keys are mapped to arbitrary scan codes (such as `F1`~`F12` and `Left Shift`) by the TV OS. The Tizen embedder uses the scan codes as they are and it doesn't provide any special mapping solely for them. This results in some weird physical-to-logical key mapping, for example, `XF86AudioRaiseVolume` is logically mapped to `F10`, but not `audioVolumeUp` as the user may expect. I don't think this is our problem, and the TV input system team should clean up this mess.

One exception for this is the `XF86AudioPlayPause` and `XF86SysMenu` keys. This special mapping has been introduced to avoid key conflicts (for example `XF86SysMenu` was originally mapped to `Left Shift` and it resulted in an error).

https://github.com/flutter-tizen/engine/blob/f6a2e2efab13553e82232343d52da5b66208942b/shell/platform/tizen/channels/key_event_channel.cc#L38-L44

FYI) There will be some changes to the key mapping as https://github.com/flutter-tizen/engine/issues/221 will be implemented. The above issue will still remain there as long as the fundamental problem is not gone.

**Comment by swift-kim** [comment]
Notice: There will be some breaking change to our embedder's physical key mapping. Please refer to https://github.com/flutter-tizen/flutter-tizen/pull/391 and consider migrating to the HardwareKeyboard-based API if you're using the legacy RawKeyboard-based API.

I also created a [wiki page](https://github.com/flutter-tizen/flutter-tizen/wiki/Key-mapping) that contains a full list of keys that are known to both Tizen and Flutter.
