### ISSUE TITLE
FlutterView prototype (with EFL EvasGL)

### ISSUE THREAD

**Issue by JSUYA** [flutter-tizen/flutter-tizen#325]
![flutter-tizen-flutterview_test_0208-2](https://user-images.githubusercontent.com/7413838/153111164-37c44cc0-254d-466c-9f3e-924bf6f14656.gif)

I made a prototype of a simplest(?) FlutterView.
https://github.com/flutter-tizen/engine/issues/233 + https://github.com/JSUYA/flutter-tizen/commit/458bb1313baa67590f0a71f115d643267793f9f1
I referenced FlutterApp class.

I haven't checked FlutterView of Windows yet. This prototype was made just for create several engine instances and test the entryPoint of the dart code.
I am planning a structure that Tizen-EFL application developer can get EFL Object (Evas_Object) when creating FlutterView and specifying entryPoint of appropriate dart code.
I need a lot of opinions....

Run command
`$ flutter-tizen run -t lib/main.dart`

Dart code
```dart
import 'package:flutterview_test/item1.dart' as item1;
import 'package:flutterview_test/item2.dart' as item2;

void main() {
  // Nothing to do
}

@pragma('vm:entry-point')
void main1() {
  runApp(const item1.MyApp());
}

@pragma('vm:entry-point')
void main2() {
  runApp(const item2.MyApp());
}
```

C code example
```cpp
FlutterView view;
view.height_ = 500; // Size
view.parent = box; // Parent is must need.
view.SetDartEntrypoint("main1"); //Optional, Default is "main"
view.RunEngine();

if (view.IsRunning()) {
  Evas_Object* image = (Evas_Object*)(view.GetImageHandle());
  evas_object_size_hint_weight_set(image, EVAS_HINT_EXPAND, EVAS_HINT_EXPAND);
  evas_object_size_hint_align_set(image, EVAS_HINT_FILL, EVAS_HINT_FILL);
  elm_box_pack_end(box, image);
}
```

+)
This prototype is not perfect for touch events. (The touch event is not delivered to the second view. I haven't fully understood touch_event_handle.cc yet...)

**Comment by JSUYA** [comment]
FlutterView can be similar to this.
https://github.com/flutter-tizen/engine/issues/94
However, the most important point in FlutterView is a way to add dart compile and Flutter Engine in the existing Tizen-EFL app by nice interface.

**Comment by bbrto21** [comment]
related issue https://github.com/flutter-tizen/flutter-tizen/issues/351
