### ISSUE TITLE
Soft keypad for TextField doesn't work properly in Tizen TV 6.5.

### ISSUE THREAD

**Issue by Kyungeun-Park** [flutter-tizen/flutter-tizen#327]
I found some issues about the soft keypad while using TextField in Tizen TV 6.5 binary.

- no response for some buttons, switching number mode, setting, backspace, space, confirm, <, > when entered by the remote controller or the keyboard connected to the TV(but it's working properly for the mouse input).
- needs to press a number key twice time for the keyboard to enter the number into TextField .
  i.e. press a number key > the soft keypad is shown but the number is not entered into TextField > press the number key again > the number is entered into it.
- 'keyboardType: TextInputType.number' is not working. As flutter guide, it shows only numbers but it doesn't. It shows as below.

![keypad issue](https://user-images.githubusercontent.com/12387465/153192372-3a031422-58aa-42d0-8cb4-b2f3117a9953.jpg)

**Comment by bbrto21** [comment]
@Kyungeun-Park 

As I explained briefly over the company messenger, this problem occurs because the engine did not send the key-up event to  `imf context`. 

To explain in more detail, recently, the software keyboard on TV has been updated with long press event implementation, and if the key-up event does not occur quickly, it will be treated long press event.

I'll fix it as soon as possible. thank you.

**Comment by bbrto21** [comment]
@Kyungeun-Park Recently, latest flutter-tizen that including fix this issue was released. could you try using the latest version?

**Comment by Kyungeun-Park** [comment]
I updated flutter-tizen with the latest version by git pull and tried to reproduce issues above again.

I figured out that the issues were fixed except the one issue that 'keyboardType: TextInputType.number' is not working.
I expect the soft keypad for only numbers input. Could you check it again?

Thank you for your support.

**Comment by bbrto21** [comment]
> I figured out that the issues were fixed except the one issue that 'keyboardType: TextInputType.number' is not working.

@Kyungeun-Park  Sorry for the late reply I was working on another task for a while. 

I contacted the person in charge of VD IME. he told me that "number only layout is not supported".
here is supported type list
```
ECORE_IMF_INPUT_PANEL_LAYOUT_NORMAL
ECORE_IMF_INPUT_PANEL_LAYOUT_EMAIL
ECORE_IMF_INPUT_PANEL_LAYOUT_PASSWORD
ECORE_IMF_INPUT_PANEL_LAYOUT_URL
```
Therefore, unlike other profiles of Tizen, number layout cannot be used on TV.

**Comment by swift-kim** [comment]
Well, technically there is a "number keypad" on TV but it's unfortunate that the TV IME system doesn't support it.

![T-samsung-6 0-x86-2022-03-16-183348](https://user-images.githubusercontent.com/40190588/158560201-5b0a7515-8fad-4ef9-83df-8fa1571e4124.png)

**Comment by bbrto21** [comment]
I asked if he had any plans to support it in the near future, he replied that he had no plans at the moment :(

**Comment by bbrto21** [comment]
This is naturally solved if the VD's software keyboard supports number only layout. So, if there are no further comments, I will close this issue.

**Comment by Kyungeun-Park** [comment]
I agree with you.
