### ISSUE TITLE
Tizen platform in pubspec.yaml

### ISSUE THREAD

**Issue by lenchis001** [flutter-tizen/flutter-tizen#328]
Hello, guys!

I have a question about flutter-tizen internal codebase. As we can see from this pubspec: https://github.com/flutter-tizen/plugins/blob/master/packages/package_info_plus/pubspec.yaml you've added "tizen" as a supported platform. (line 10)

Could you please point the place in flutter-tizen codebase which you implemented/changed to add support of this?

We also need to add support of a non-default platform.

Thanks.

**Comment by swift-kim** [comment]
The `tizen` key is defined here:
https://github.com/flutter-tizen/flutter-tizen/blob/562106e13aba50dce73d593a8ea34ca2561a1bbd/lib/tizen_plugins.dart#L63

And it's invoked by:
https://github.com/flutter-tizen/flutter-tizen/blob/562106e13aba50dce73d593a8ea34ca2561a1bbd/lib/tizen_plugins.dart#L369-L373

To obtain the runtime stack trace (call stack), you may want to read [Debugging the flutter-tizen tool](https://github.com/flutter-tizen/flutter-tizen/wiki/Debugging-the-flutter%E2%80%91tizen-tool).

**Comment by lenchis001** [comment]
Thanks!
