### ISSUE TITLE
URL redirect for video player 

### ISSUE THREAD

**Issue by xuelian-bai** [flutter-tizen/flutter-tizen#330]
@swift-kim For example: in case of Web App, we can use Shaka Player by Google.

When Shaka plays some content, it makes requests for video content (manifest, chunks - parts of video and audio) - look at screenshot.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15190316/152935127-2d94c8c0-e666-4739-b173-f0cf523629cb.png">

We need to be able to set a callback function, which will be called by player before making every requests (manifest and chunks) to be able to modify the url. For example:

1. Player wants to fetch a video chunk with URL: http://www.example.com/videos/birds/replace_with_user_id/video_chunk_12.webm
2. Before making the request with this URL it calls our function, something like this:
(url) => url.replaceAll("replace_with_user_id", "12345")
3. Eventually player will request this chunk by URL:
http://www.example.com/videos/birds/12345/video_chunk_12.webm

_Originally posted by @lenchis001 in https://github.com/flutter-tizen/flutter-tizen/issues/217#issuecomment-1032286873_

**Comment by lenchis001** [comment]
@xuelian-bai Hello, yes it's DASH + Widevine

**Comment by xuelian-bai** [comment]
ok, I'm not sure if there is such requirement(dynamicly replace URL ) in DASH protocol

**Comment by lenchis001** [comment]
@xuelian-bai Yes, it's not. We need such logic as a player extension.

**Comment by lenchis001** [comment]
I found a hack for this: I create an in-app HTTP server and make all player requests though this.

For example:
1. Run HTTP server on port 8089;
2. Change manifest from http://cdn.com/some_stream.mpd -> http://localhost:8089/some_stream.mpd
That's it.

Local HTTP server is configured to redirect requests to http://cdn.com and allow to make URL transformation via MethodChannel's.

**Comment by swift-kim** [comment]
Please re-open if there's any plan for supporting this feature.
