### ISSUE TITLE
dotnet plugins

### ISSUE THREAD

**Issue by lenchis001** [flutter-tizen/flutter-tizen#332]
Hello everyone. I found your repository https://github.com/flutter-tizen/plugins . As I can see you use C++ for plugins. Is it possible to use C# instead of C++? Is there any sample of such plugin?

**Comment by lenchis001** [comment]
@swift-kim Thanks man! I’ll try.

**Comment by WonyoungChoi** [comment]
@lenchis001 I have a plan to support `dotnet plugin` officially in `flutter-tizen`. Please refer #333.
