### ISSUE TITLE
Failed to connect to the device logger.

### ISSUE THREAD

**Issue by Vagharsh75** [flutter-tizen/flutter-tizen#357]
Failed to connect to the device logger.

**Comment by swift-kim** [comment]
Could you provide some details, including the `flutter-tizen doctor -v` result and your device model and version, so that we can reproduce the error?

**Comment by Vagharsh75** [comment]
Thank you
My Samsung TV Tizen version is 4.0

Tizen UE43N5300 (mobile) • 192.168.40.81:26101 • flutter-tester • Tizen 4.0 (unsupported)

**Comment by swift-kim** [comment]
Yes, the error is expected because Flutter apps cannot launch on Tizen 4.0 TV devices.
