### ISSUE TITLE
[Feature Request] Support config to set path to Tizen Studio

### ISSUE THREAD

**Issue by adityaaswani** [flutter-tizen/flutter-tizen#362]
Is there a way where we can set the path to Tizen Studio if the TS is installed in a custom path.
If not, is it possible to get an option to set Tizen Studio Path config, just like there is a config to set the path to android studiio.

**Comment by swift-kim** [comment]
You can set the TIZEN_SDK environment variable as necessary.
```
$ flutter-tizen doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.10.1, on Ubuntu 20.04.2 LTS 4.19.128-microsoft-standard, locale C.UTF-8)
[✗] Tizen toolchain - develop for Tizen devices
    ✗ Unable to locate Tizen SDK.
      Install Tizen Studio from: https://developer.tizen.org/development/tizen-studio/download
      If the Tizen SDK has been installed to a custom location, set TIZEN_SDK to that location.
```
If the variable is not set, the tool checks for the sdb location (`which sdb`), and if it's still not found, the tool finally looks for the default location (`~/tizen-studio`).
