### ISSUE TITLE
flutter app crash발생관련 문의

### ISSUE THREAD

**Issue by yman-son** [flutter-tizen/flutter-tizen#374]
안녕하세요!
Flutter Application개발/테스트 중 발생하는 예외상황에 대한 callStack정보를 어떻게 얻을 수 있는지에 대한 문의를 하려고 합니다. 

Flutter App (Dart code), Flutter Plugin, Flutter Engine
위의 3가지 타입의 코드에서 예외 상황이 발생할 수 있을 것 같습니다. 

Null Safety에 의해 null access가 발생할 가능성이 거의 없으나, 다른 예외 상황으로 인하여 crash발생시 
Flutter App(Dart code), Flutter Plugin의 경우 아래와 같이 dlogutil의 console Message나 VS code상에 리포트를 하는 부분을 확인했습니다.
_Assertion failed: "This platform is currently unsupported by webview_flutter."
When the exception was thrown, this was the stack:
#0      new CookieManager._ (package:webview_flutter/src/webview.dart:806:9)
#1      new CookieManager (package:webview_flutter/src/webview.dart:796:40)
#2      main.<anonymous closure> (file:///C:/flutter-tizen/plugins/plugins/packages/webview_flutter/example/integration_test/webview_flutter_test.dart:489:41)_
혹시 이외에  dart code에 의해 C++ 바이너리처럼 coredump가 발생하는 crash도 있을 수 있는지 궁금합니다.

또한 Flutter Engine은 대부분 C++ code로 되어 있는데요. 
이 코드에서 crash되어 발생하는 coredump는 어떻게 callstack을 얻을 수 있을지 공유 부탁 드립니다. 

감사합니다.

**Comment by swift-kim** [comment]
제가 TV에서 디버깅해본 적은 없지만 LLDB (혹은 GDB) 사용이 가능한 것으로 알고 있고 따라서 아래를 보시면 될 것 같습니다.

https://github.com/flutter-tizen/flutter-tizen/wiki/Debugging-app's-native-code

Live debugging이 아닌 crash dump로부터의 디버깅은 아래쪽의 "Debugging core dumps" 부분을 보시면 됩니다. 플러그인 코드의 경우 디버그 모드로 실행하시면 symbol 정보가 남아있기 때문에 stacktrace를 보실 수 있고, embedder나 engine의 경우 기본적으로 symbol이 strip되어서 배포되기 때문에 그 아래 부분을 참고하셔서 symbol 파일을 수동으로 추가해주시면 됩니다.

그 외 Flutter 관련이 아닌 내부 system library 관련 문제는 예전엔 블루펄을 썼던 걸로 기억합니다.

**Comment by yman-son** [comment]
답변 감사합니다!
