### ISSUE TITLE
Introduce FlutterEngine

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/flutter-tizen#380]
Essentially, the engine can run independently of the view and can be cached. This gives us flexibility and can also benefit from performance, such as improved launch times. 
Furthermore I guess that FlutterEngine and ElmFlutterView may lead us to efficiently support Tizen's widget application.

_Originally posted by @bbrto21 in https://github.com/flutter-tizen/flutter-tizen/pull/373#discussion_r896401459_

**Comment by JSUYA** [comment]
If we can reuse and caching FlutterEngine, we can think about FlutterEngineGroup together.
https://docs.flutter.dev/development/add-to-app/multiple-flutters#components

**Comment by bbrto21** [comment]
[this](https://github.com/flutter-tizen/flutter-tizen/pull/382) is first draft. I experimentally applied this only to `ElmFlutterView`.
It is expected that it can be applied to other flutter host types(app, service), and a similar architecture can be applied to C#.

I am also considering that wrap FlutterDesktopViewRef as `FlutterView`. 
`FlutterView` will play a similar role to `FlutterEngine`, and I think it can be used as an `is-a` or `has-a` relationship in other classes.

**Comment by swift-kim** [comment]
Implemented in https://github.com/flutter-tizen/flutter-tizen/pull/382.

**Comment by bbrto21** [comment]
Similar designs can be applied to C# embeddings. but this is a low priority item for me.

**Comment by swift-kim** [comment]
The C# version is available in https://github.com/flutter-tizen/flutter-tizen/pull/390.

**Comment by swift-kim** [comment]
Future works:
- [ ] Create the `FlutterView` class.
- [ ] Add support for `FlutterEngineGroup` (requires adding a spawn API to the embedder).

These might be tracked by separate issues. The second one is related to https://github.com/flutter-tizen/engine/issues/94.

**Comment by bbrto21** [comment]
> * [ ]  Create the `FlutterView` class.

May I start working on this?

**Comment by swift-kim** [comment]
@bbrto21 Sure. The work seems to be part of https://github.com/flutter-tizen/flutter-tizen/issues/351 and the progress may be tracked there.
