### ISSUE TITLE
Pre-validate on Tizen 7.0

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/flutter-tizen#383]
Tizen 7.0 will be released this year, and we should be pre-tested the flutter-tizen for that release.
basically, Tizen APIs we use in engine and plugin implementations, guarantee backwards compatibility, so there should be no problems.
nevertheless, basic flutter-tizen behavior, sample, plug example behavior and all tests should be pre verified on emulators and test devices.

If you have any flutter-tizen issues on Tizen 7.0, please track an issues at here.

**Validation Items**
Item | TV Device | TV Emulator | Wearable Device | Wearable Emulator | RPi4 | Mobile Device(TM1) | Mobile Emulator|
|-|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
Flutter Gallery app | | | |✔️| ✔️|✔️|✔️|
Example of plugins | | | |✔️| |✔️|✔️|
Integration test of plugins |-| |-|✔️|-|-|-|

**Comment by swift-kim** [comment]
I verified the Flutter Gallery app on RPi4 (arm64) and everything was functional.

```sh
$ cat /etc/os-release
NAME=Tizen
VERSION="7.0.0 (Tizen7/Unified)"
ID=tizen
VERSION_ID=7.0.0
PRETTY_NAME="Tizen 7.0.0 (Tizen7/Unified)"
ANSI_COLOR="0;36"
CPE_NAME="cpe:/o:tizen:tizen:7.0.0"
BUILD_ID=tizen-unified_20220706.2_tizen-headed-aarch64
```

**Comment by WonyoungChoi** [comment]
Don't we need an end-to-end test for Tizen?
https://github.com/flutter/flutter/wiki/Testing-the-engine#end-to-end-tests

**Comment by bbrto21** [comment]
> I verified the Flutter Gallery app on RPi4 (arm64) and everything was functional.

I verified the Flutter Gallery app on TM1 too.
```
NAME=Tizen
VERSION="7.0.0 (Tizen7/Unified)"
ID=tizen
VERSION_ID=7.0.0
PRETTY_NAME="Tizen 7.0.0 (Tizen7/Unified)"
ANSI_COLOR="0;36"
CPE_NAME="cpe:/o:tizen:tizen:7.0.0"
BUILD_ID=tizen-unified_20220624.1_mobile-wayland-armv7l-tm1

```

**Comment by bbrto21** [comment]
> Don't we need an end-to-end test for Tizen? https://github.com/flutter/flutter/wiki/Testing-the-engine#end-to-end-tests

From the early stages of the project, we knew the existence of end-to-end testing and briefly reviewed it, but we have not yet introduced it. I think this is a necessary test for flutter-tizen apart from the pre-verification for the Tizen 7.0 release.

**Comment by swift-kim** [comment]
Do we still need this activity?

**Comment by bbrto21** [comment]
@swift-kim 
I'm validating flutter-tizen with Tizen7.0 on various devices and emulators my self.
Do you know how to install a TV emulator for Tizen 7.0?

**Comment by swift-kim** [comment]
Tizen 7.0 has been released.
