### ISSUE TITLE
SD site에 Flutter-tizen image사용문의

### ISSUE THREAD

**Issue by yman-son** [flutter-tizen/flutter-tizen#396]
안녕하세요!

samsung developers사이트에 Flutter guide 작성 중 Flutter공식 이미지에 대한 법무검토 결과
사용하지 않는 것이 좋겠다는 가이드를 받았습니다. 

이에 따라 flutter logo를 넣으려고 했던 위치에 flutter-tizen page에 있는 이미지를 추가하려고 합니다. 
https://github.com/flutter-tizen/flutter-tizen/raw/master/doc/images/flutter-tizen.png

이것을 사용해도 될지 답변 부탁 드립니다.

작성중인 가이드 : http://wiki.vd.sec.samsung.net/pages/viewpage.action?pageId=172067006
감사합니다.

**Comment by swift-kim** [comment]
네, 제약 없이 사용하실 수 있습니다.

그런데 Flutter 공식 로고를 사용하셔도 문제가 없을 거라고 생각되는데요. (저희 이미지도 공식 로고를 변형시킨 것이니 안 될 거면 둘 다 안 되어야 하는 게 아닐까..)

https://docs.flutter.dev/brand
