### ISSUE TITLE
Support Flutter-Tizen as a module

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/flutter-tizen#397]
As a first step to provide a way to easily porting Flutter-Tizen to an existing Tizen project, we can consider supporting the below instruction set.

```
cd ~/existing_tizen_project_path/
flutter-tizen create -t module ./some-flutter-tizen-module
flutter-tizen build sharedLib
```

In order to provide flutter-tizen as a sharedLib, the module should not have an entry point in the native area, and the public header of the `embedding` should be exposed in the built sharedlib.

Intuitively, you can imagine the build output like the one below.
ls ~/existing_tizen_project_path/some-flutter-tizen-module/build
```
build/
└── tizen
    └── sharedLib
         ├── include
         │   ├── HEADER_FILES_OF_EMBEDDING
         │   ├──  ......
         ├── lib
         │   ├── libapp.so
         │   ├── libflutter_engine.so
         │   └── libflutter_tizen_mobile.so
         ├── res
         │   ├── flutter_assets
         │   │   ├── AssetManifest.json
         │   │   ├── FontManifest.json
         │   │   ├── fonts
         │   │   │   └── MaterialIcons-Regular.otf
         │   │   ├── NOTICES.Z
         │   │   └── packages
         │   │       └── cupertino_icons
         │   │           └── assets
         │   │               └── CupertinoIcons.ttf
         │   └── icudtl.dat
         └── libsome-flutter-tizen-module.so
```
After that, the user can manually set dependency and use a module in the existing tizen project.
Oh, of course, the user has to write the program manually using the set of public API provided by the embedding headers.
I think there are many loopholes in this draft. Let's discuss it together.

**Comment by WonyoungChoi** [comment]
So... do users have to copy the embedding headers and flutter related .so files directly to existing projects?

**Comment by bbrto21** [comment]
I imagined the directory would be organized like this after execution of `module` command

`ls ~/existing_tizen_project_path/some-flutter-tizen-module`
```
some-flutter-tizen-module/
├── lib
│   └── main.dart
├── pubspec.yaml
├── README.md
└── test
    └── widget_test.dart
```
and after build a module, since it is already located under the existing Tizen project, I thought the user could set up dependencies immediately without copying. of course, users must change the project configuration to include the built modules into the app package(tpk)

As you mentioned, I think If the user created the module in some place other than the existing Tizen project, then user can copy the sharedLib directory to use it.

It would be better if we could minimize user's configurations, but as a first step, I thought up to here.

**Comment by swift-kim** [comment]
The user can create a sharedLib project in an arbitrary location and reference it from a native UI app project (without having to manually copy files) using the "Multi Package" feature. The feature worked greatly in Tizen Studio but I'm still not sure how to make it work with Tizen CLI.

Also we need to consider .NET (C#) projects before finalizing the design. Even if we don't yet support the add-to-app feature for C# apps, the fundamental design and architecture should be the same for both app languages.

Question: Does the module project in your above design have any user code in its `src` directory? Is `libsome-flutter-tizen-module.so` just a compiled C++ embedding without any user code? How will the embedding source code get compiled in that case?

**Comment by bbrto21** [comment]
I didn't think of this until you mentioned it. If "Multi Package" feature works well with Tizen CLI, flutter-tizen module support will be easier. 

and as you said, even if C# support doesn't come right away, we should always consider this. thank you for reminding me.

I assumed that there would be no `src` directory in the module directory. I haven't actually tried it, but I imagined that it wouldn't be much different from plugin builds in that there is no entry point and the build result is a shared library. @swift-kim Do you think this is a possible direction?

**Comment by swift-kim** [comment]
> I haven't actually tried it, but I imagined that it wouldn't be much different from plugin builds in that there is no entry point and the build result is a shared library.

Hmm. I was asking "how" you were going to compile the library (i.e. where to place the `project_def.prop` file and how to configure it).

**Comment by swift-kim** [comment]
Regarding the multi package build, I asked the Tizen SDK team for how to configure the build.

We also have to consider how to support "plugin registration" of the module. Obviously, all headers (`generated_plugin_registrant.h` and individual plugin headers) should be added to the include paths during app build.

**Comment by bbrto21** [comment]
I assumed to use a hidden directory if necessary.
`ls ~/existing_tizen_project_path/some-flutter-tizen-module`
```
some-flutter-tizen-module/
├── .tizen
     └── project_def.prop
...
```
I'm verifying these assumptions in the simplest form I can. If there is any progress, I will share it with you.

**Comment by bbrto21** [comment]
I verified that embedding flutter tizen to existing project is available for the two cases below manually.
1. Use static library of `embedding` from `flutter-tizen`, In this case, you need that:
   - Include the following three libraries in existing project:  
       - `libembedding_cpp.a` (this is a byproduct produced by the tool.)
       - `libflutter_engine.so`
       - `libflutter_tizen_mobile.so`
   - Add dependencies for the three libraries.
   - Add include path for header files. those headers are in `flutter-tizen`.
       - embedding/cpp/include
       - tizen-common/public
       - tizen-common/cpp_client/wrapper/include
   - Add linker options : `--unresolved-symbols=ignore-in-shared-libs`

Therefore, it seems that we can use project_def.prop, which is in `embedding/cpp` in tool, and we can use most of the existing build flows for building a module.

2. Use a shared library. for this, I created a project for shared library and It was based on copied `embedding` files from flutter-tizen. In this case, you need that:
   - Include the following three libraries in existing project:  
      - `libembedding_module.so`
      - `libflutter_engine.so`
      - `libflutter_tizen_mobile.so`
   - Add dependency about `libembedding_module.so`(`libembedding_module.so` to depend on rest libs )
   - Add include path for header files in shared lib project. 
   - Add linker options : `--unresolved-symbols=ignore-in-shared-libs`

**Comment by bbrto21** [comment]
As a result of the previous consideration, I have derived the following requirements.

- Executing `create -t ​​module ./some_module` should make the following directory structure.
    ```
      some_module/
      ├── lib
      │   └── main.dart
      ├── pubspec.yaml
      ├── README.md
      └── test
          └── widget_test.dart
    ```
    - This is a minimum configuration for the flutter project.
    - It seems that Tizen dependent files are not needed as of now.
- Executing `build staticLib -pmobile` should make the following directory structure.
  ```
  build/
  └── tizen
      ├── staticLib // output dir for module
      │   ├── inc
      │       ├── HEADER_FILES_OF_EMBEDDING_CPP
      │       ├── HEADER_FILES_OF_TIZEN_COMMON_PUBLIC
      │       ├── HEADER_FILES_OF_TIZEN_COMMON_CPP_CLIENT_WRAPPER
      │       └── generated_plugin_registrant.h
      │   ├── lib
      │   │   ├── tizen-arm64-debug
      │   │   ├── tizen-arm64-profile
      │   │   ├── tizen-arm64-release
      │   │   ├── tizen-arm-debug
      │   │   ├── tizen-arm-profile
      │   │   ├── tizen-arm-release
      │   │   └── tizen-x86-debug
      │   │       ├── libembedding_cpp.a
      │   │       ├── libflutter_engine.so
      │   │       ├── libflutter_tizen_mobile.so
      │   │       └── libflutter_plugins.so
      │   └── res
      │       ├── flutter_assets
      │       └── icudtl.dat
      └── tpk // output dir for tpk
  
  ```
   -  Since `build` will make `embedding/cpp` as a static library, we can use `project_def.prop` located in `embedding/cpp` to build
   - To allow users to embed a flutter into existing apps using only output of `build`, the output should include all relevant header files.(even if `flutter-tizen` is not installed in users's host environment.)
  - `lib` must be prepared for all supported architectures and build types.
  - To load plugin, `generated_plugin_registrant.h` must provided

**Comment by JSUYA** [comment]
>  Is there anything else we should consider?

Shouldn't AOT file be included regardless of build mode?

**Comment by swift-kim** [comment]
I'll open a PR once https://github.com/flutter-tizen/flutter-tizen/pull/393 is merged.

**Comment by swift-kim** [comment]
Further discussions:
- How can we prevent `libembedding_cpp.a` from being included in the final TPK?
- Can we avoid manual file copying and instead support the "multi package" build? (I left a question [here](https://github.sec.samsung.net/RS-TizenStudio/home/issues/253) and waiting for a reply.)
- Should the built module contain libs for all archs and profiles by default, or should the user always specify a build arch and profile for the `build module` command?
- How do you like the command name (`build module`)? I'm currently planning to use the same command for both native and .NET builds.

**Comment by bbrto21** [comment]
> * Should the built module contain libs for all archs and profiles by default, or should the user always specify a build arch and profile for the `build module` command?

I prefer the first one. and we can find similar structure in the [webview_flutter_tizen
](https://github.com/flutter-tizen/plugins/tree/master/packages/webview_flutter/tizen/lib)

> * How do you like the command name (`build module`)? I'm currently planning to use the same command for both native and .NET builds.

I like it :)

**Comment by swift-kim** [comment]
The embedding by default expects `libapp.so` to be located directly under the `lib` directory, so it will be problematic if the directory structure looks like:

```sh
lib
└── tizen-x86-debug
    ├── libapp.so
    ├── libembedding_cpp.a
    ├── libflutter_engine.so
    └── libflutter_tizen_mobile.so
```

**Comment by bbrto21** [comment]
How about choosing the default path at compile time? I think we can make an intermediate path from the build information and put it into tizen CLI as a predefine when building embedding. 

> should the user always specify a build arch and profile for the build module command?

Are there any expected problems when choosing this?

**Comment by swift-kim** [comment]
> Are there any expected problems when choosing this?

No, the current draft is based on that approach and the build commands look very consistent:

```sh
$ flutter-tizen build tpk -pmobile --debug --target-arch x86
$ flutter-tizen build module -pmobile --debug --target-arch x86
```

**Comment by bbrto21** [comment]
It makes sense. choose the second option and let's leave the rest to the user who want to integrate flutter.

**Comment by swift-kim** [comment]
Documentation will be added to the wiki. See the PR comments until then.

- https://github.com/flutter-tizen/flutter-tizen/pull/405
- https://github.com/flutter-tizen/flutter-tizen/pull/431
