### ISSUE TITLE
App Icon Changing

### ISSUE THREAD

**Issue by raynoryip** [flutter-tizen/flutter-tizen#400]
Hi Flutter-Tizen Team,

May I ask how can I change the app icon of a Tizen App by using your framework. 
I was using **"flutter_launcher_icons"** for my non-Tizen App, but currently I don't see it officially support by your team. 

Thank You.

**Comment by swift-kim** [comment]
Hi.

The **flutter_launcher_icons** package doesn't seem to support the Tizen platform. You have to manually copy the image file to `tizen/shared/res/ic_launcher.png` in your project. You can modify the `<icon>` element of `tizen/tizen-manifeset.xml` if you have a different file name.

**Comment by raynoryip** [comment]
> Hi.
> 
> The **flutter_launcher_icons** package doesn't seem to support the Tizen platform. You have to manually copy the image file to `tizen/shared/res/ic_launcher.png` in your project. You can modify the `<icon>` element of `tizen/tizen-manifeset.xml` if you have a different file name.

Ok, thanks Kim!
