### ISSUE TITLE
Dart SDK upgrade

### ISSUE THREAD

**Issue by Thomas-Ahn** [flutter-tizen/flutter-tizen#409]
one of external package is required Dart 2.17.1 but current flutter-tizen dart version is Dart version 2.17.0,

Because flextizen depends on youtube_data_api >=1.0.0+1 which requires SDK version >=2.17.1 <3.0.0, version solving failed.

please let me know how to upgrade Dart SDK..

**Comment by adilwahla** [comment]
@Thomas-Ahn hey follow these steps any one will resolve this :

1.  _flutter upgrade_ command then wait till it automatically upgrades to the latest versions 
2. follow this video [https://youtu.be/0QC7S1nUmpY]
3. you can download particular sdk  [https://dart.dev/get-dart]

if any of above doesn't work please let me know I will be available for you any time

**Comment by adilwahla** [comment]
> one of external package is required Dart 2.17.1 but current flutter-tizen dart version is Dart version 2.17.0,
> 
> Because flextizen depends on youtube_data_api >=1.0.0+1 which requires SDK version >=2.17.1 <3.0.0, version solving failed.

Type "flutter upgrade" in your terminal this should work

**Comment by Thomas-Ahn** [comment]
flutter show 2.17.6, but flutter-tizen show 2.17.0, they are different event after flutter upgrade..

macmini@Macs-Mac-mini flextizen % flutter-tizen doctor -v            
[✓] Flutter (Channel unknown, 3.0.0, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 3.0.0 at /Users/macmini/flutter-tizen/flutter
    • Upstream repository unknown
    • Framework revision ee4e09cce0 (3 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
    
macmini@Macs-Mac-mini flextizen % flutter doctor -v      
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 3.0.5 at /Users/macmini/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Comment by swift-kim** [comment]
https://docs.flutter.dev/development/tools/sdk/releases?tab=linux

We need to upgrade the Flutter engine to at least 3.0.1. Let me update our engine and tool to 3.0.5. I'll open a PR and let you know when done.

**Comment by Thomas-Ahn** [comment]
ok, noted..

**Comment by swift-kim** [comment]
Here's the fix: https://github.com/flutter-tizen/flutter-tizen/pull/412

It's under review but you can manually cherry-pick the commit.
