### ISSUE TITLE
TV SDK could not be found

### ISSUE THREAD

**Issue by Thomas-Ahn** [flutter-tizen/flutter-tizen#410]
tizen-ide show TV SDK installed, but i got following error:

% flutter-tizen run -d emulator-26101
Using hardware rendering with device Tizen T-samsung-6.5-x86. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching tizen/flutter/generated_main.dart on Tizen T-samsung-6.5-x86 in debug mode...
Invalid depfile:
/Users/macmini/Project/qubitm/flextizen/.dart_tool/flutter_build/a3ad22c45e51c30ce862b451fb93e32a/kernel_snapshot.d
Invalid depfile:
/Users/macmini/Project/qubitm/flextizen/.dart_tool/flutter_build/a3ad22c45e51c30ce862b451fb93e32a/kernel_snapshot.d
TV SDK could not be found. Trying with Wearable SDK...

The WEARABLE SDK was installed while flutter-tizen installation.. but not sure how to install TV SDK for flutter-tizen.
/Users/macmini/tizen-studio/package-manager/package-manager-cli.bin install WEARABLE-4.0-NativeAppDevelopment-CLI

**Comment by swift-kim** [comment]
That's normal. The TV SDK is not publicly available (it's for 1st-party apps only) so the tool automatically falls back to the Wearable SDK.

**Comment by Thomas-Ahn** [comment]
do you means our company need to officially request the SDK via samsungdforum.com/B2B..

**Comment by swift-kim** [comment]
No, you can't get the SDK even if you or your company become a partner. Only 1st-party apps (published by Samsung) can be built with the TV native SDK. You'll need the SDK only if your Flutter app depends on one or more native plugins (not packages). All our published plugins are compatible with the Wearable SDK so you'll not have any problem with building the plugins.

**Comment by Thomas-Ahn** [comment]
i see, i'll try further..
