### ISSUE TITLE
image_picker_tizen  compile error on MAC

### ISSUE THREAD

**Issue by Thomas-Ahn** [flutter-tizen/flutter-tizen#411]
<package version>
image_picker: ^0.8.4
image_picker_tizen: ^2.1.0

<error message>
macmini@Macs-Mac-mini flextizen % flutter-tizen run -d emulator-26101
Using hardware rendering with device Tizen T-samsung-6.5-x86. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching tizen/flutter/generated_main.dart on Tizen T-samsung-6.5-x86 in debug mode...
TV SDK could not be found. Trying with Wearable SDK...
Exception: Failed to build image_picker_tizen plugin:
[PLATFORM] Tizen-4.0
[ARCHITECTURE] i586
[COMPILER] LLVM-10.0
[CONFIGURATION] Debug
[SBI] prdefine options = -DTV_PROFILE
[SBI] command : /bin/sh -c /usr/bin/make -f "/Users/macmini/tizen-studio/tools/ide/resources/native/Build/makefile" -r 
/Library/Developer/CommandLineTools/usr/bin/make -f /Users/macmini/tizen-studio/tools/ide/resources/native/Build/makefile.mk
preparing to build src/image_picker_tizen_plugin.cc
preparing to build src/image_resize.cc
/Users/macmini/tizen-studio/tools/ide/resources/native/Build/makefile.mk:160: warning: overriding commands for target `Debug'
/Users/macmini/tizen-studio/tools/ide/resources/native/Build/makefile.mk:157: warning: ignoring old commands for target `Debug'
  Building file: src/image_picker_tizen_plugin.cc
  Output Path ./Debug
  Invoking: C++ Compiler
  Building directory: Debug/src
"/Users/macmini/tizen-studio/tools/smart-build-interface/../llvm-10/bin/clang++" -c "src/image_picker_tizen_plugin.cc" -o
"Debug/src/image_picker_tizen_plugin.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc
-Isrc  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi -gcc-toolchain
"/Users/macmini/tizen-studio/tools/smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name i586-linux-gnueabi-g++
-march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument -fdebug-default-version=3 -std=c++17 -fPIE
--sysroot="/Users/macmini/tizen-studio/platforms/tizen-4.0/wearable/rootstraps/wearable-4.0-emulator.core"
-Werror-implicit-function-declaration  -fPIC
-I"/Users/macmini/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/Users/macmini/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public" -Wp,@./Debug/objs/platform_incs_file.inc
In file included from src/image_picker_tizen_plugin.cc:19:
src/image_resize.h:15:50: error: unknown type name 'image_util_image_h'; did you mean 'image_util_scale_e'?
  bool DecodeImage(image_util_decode_h decode_h, image_util_image_h& src_image,
                                                 ^~~~~~~~~~~~~~~~~~
                                                 image_util_scale_e
/Users/macmini/tizen-studio/platforms/tizen-4.0/wearable/rootstraps/wearable-4.0-emulator.core/usr/include/media/image_util_type
.h:158:3: note: 'image_util_scale_e' declared here
} image_util_scale_e;
  ^
In file included from src/image_picker_tizen_plugin.cc:19:
src/image_resize.h:18:23: error: unknown type name 'image_util_image_h'; did you mean 'image_util_scale_e'?
                      image_util_image_h src_image,
                      ^~~~~~~~~~~~~~~~~~
                      image_util_scale_e
/Users/macmini/tizen-studio/platforms/tizen-4.0/wearable/rootstraps/wearable-4.0-emulator.core/usr/include/media/image_util_type
.h:158:3: note: 'image_util_scale_e' declared here
} image_util_scale_e;
  ^
In file included from src/image_picker_tizen_plugin.cc:19:
src/image_resize.h:19:23: error: unknown type name 'image_util_image_h'; did you mean 'image_util_scale_e'?
                      image_util_image_h& dst_image);
                      ^~~~~~~~~~~~~~~~~~
                      image_util_scale_e
/Users/macmini/tizen-studio/platforms/tizen-4.0/wearable/rootstraps/wearable-4.0-emulator.core/usr/include/media/image_util_type
.h:158:3: note: 'image_util_scale_e' declared here
} image_util_scale_e;
  ^
In file included from src/image_picker_tizen_plugin.cc:19:
src/image_resize.h:20:50: error: unknown type name 'image_util_image_h'; did you mean 'image_util_scale_e'?
  bool EncodeImage(image_util_encode_h encode_h, image_util_image_h dst_image,
                                                 ^~~~~~~~~~~~~~~~~~
                                                 image_util_scale_e
/Users/macmini/tizen-studio/platforms/tizen-4.0/wearable/rootstraps/wearable-4.0-emulator.core/usr/include/media/image_util_type
.h:158:3: note: 'image_util_scale_e' declared here
} image_util_scale_e;
  ^
4 errors generated.
make[1]: *** [Debug/src/image_picker_tizen_plugin.o] Error 1
make: *** [app_build] Error 2
Total time: 00:00:12.679
Building a Tizen application in debug mode...                     128.0s
Exception: The build failed.

**Comment by swift-kim** [comment]
As stated in [README](https://github.com/flutter-tizen/plugins/tree/master/packages/image_picker#supported-devices), the image_picker_tizen plugin makes use of Tizen 5.5 APIs, so you have to increase your [app's target SDK version](https://github.com/flutter-tizen/plugins/blob/e5d439825c728a83695dd6215f9787c4ef868ea6/packages/image_picker/example/tizen/tizen-manifest.xml#L2) to at least 5.5.

By the way, if you're targeting TV devices, you can't use the image_picker plugin because there's no file manager or gallery app for TV as far as I know.
