### ISSUE TITLE
.NET SDK error on Mac OS

### ISSUE THREAD

**Issue by Thomas-Ahn** [flutter-tizen/flutter-tizen#413]
Does it support Mac OS or is there any configuration for Mac OS?

macmini@Macs-Mac-mini flextizen % flutter-tizen run -d emulator-26101
Running "flutter pub get" in flextizen...                          11.1s
Using hardware rendering with device Tizen T-samsung-6.5-x86. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching tizen/flutter/generated_main.dart on Tizen T-samsung-6.5-x86 in debug mode...
TV SDK could not be found. Trying with Wearable SDK...
Exception: Unable to locate .NET CLI executable.
Install the latest .NET SDK from: https://dotnet.microsoft.com/download
Building a Tizen application in debug mode...                     190.9s
Exception: The build failed.

**Comment by swift-kim** [comment]
https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/macos-install.md

You should install the .NET SDK to build Tizen apps. The latest is .NET 6.0.

**Comment by Thomas-Ahn** [comment]
thanks, now can be built, but struggling on GetX... i'll post after further debugging..
