### ISSUE TITLE
video playing on T-samsung-6.5-x86 emulator with video_player_tizen 

### ISSUE THREAD

**Issue by Thomas-Ahn** [flutter-tizen/flutter-tizen#415]
Does support playing a video on samsung TV emulator? I got blank screen..

**Comment by swift-kim** [comment]
https://github.com/flutter-tizen/plugins#device-limitations

No. video_player_tizen is not supported on TV emulator.

It works on a real TV device but some features may not be functional as stated in [README](https://github.com/flutter-tizen/plugins/tree/master/packages/video_player#limitations).

**Comment by Thomas-Ahn** [comment]
thanks for clarification!
