### ISSUE TITLE
Touch screen not working on Tizen 4.0

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#424]
Flutter apps ignore all keyboard and touch events on Tizen 4.0 (wearable) emulator.

@bbrto21 @JSUYA Can you reproduce the issue?

**Comment by bbrto21** [comment]
@swift-kim You are right, I reproduced this issue simply on Tizen 4.0 (wearable) emulator :cry:

**Comment by bbrto21** [comment]
I also found a problem with the software keyboard not showing up on Tizen 4.0 (wearable) emulator. :disappointed:

**Comment by bbrto21** [comment]
@swift-kim Could you test [this PR?](https://github.com/flutter-tizen/engine/pull/329)
