### ISSUE TITLE
Change Version in Tizen-manifest.xml

### ISSUE THREAD

**Issue by raynoryip** [flutter-tizen/flutter-tizen#438]
Hi Flutter-Tizen Team,

I have uploaded the tpk file to the Samsung TV Apps portal, Samsung team asked me to change the version of my app, which is by default 1.0.0. 
I tried to modify it from { version="1.0.0" } to { version="1.0.1"}  in my VS Code and hit save and then run { flutter-tizen build tpk --device-profile tv }, but the version keep revert back to 1.0.0. And I don't know why and how could I change it. May you please advise me a solution?

**Comment by swift-kim** [comment]
Hi.

If the version of the flutter-tizen tool you're using is older than https://github.com/flutter-tizen/flutter-tizen/commit/141255ea9bca935192ed8b2e4357a77b3a9b2174, the package version in `tizen-manifest.xml` is automatically updated based on the app version specified in your `pubspec.yaml` during build. If you update flutter-tizen to the latest, the tool will no longer modify the content of `tizen-manifest.xml`.

**Comment by raynoryip** [comment]
> Hi.
> 
> If the version of the flutter-tizen tool you're using is older than [141255e](https://github.com/flutter-tizen/flutter-tizen/commit/141255ea9bca935192ed8b2e4357a77b3a9b2174), the package version in `tizen-manifest.xml` is automatically updated based on the app version specified in your `pubspec.yaml` during build. If you update flutter-tizen to the latest, the tool will no longer modify the content of `tizen-manifest.xml`.

Appreciate your help Kim, you are very helpful :)
