### ISSUE TITLE
Is support webview?

### ISSUE THREAD

**Issue by oysterlab** [flutter-tizen/flutter-tizen#45]
Could I use sort of webview  for Tizen smart TV?

**Comment by bwikbs** [comment]
Currently, It is under development at here (https://github.com/flutter-tizen/plugins/tree/webview_devel) and you can run example of that at TV.

**Comment by swift-kim** [comment]
Implementing the [webview plugin](https://github.com/flutter/plugins/tree/master/packages/webview_flutter) for Tizen will take some time. So unfortunately the answer is no.

@bwikbs 2021 TV models are not released yet so there's no way to run the example outside the company. It's unable to load .so files on older models.
