### ISSUE TITLE
Is there an inapp purchase plugin for tizen appstore ?

### ISSUE THREAD

**Issue by nassimus26** [flutter-tizen/flutter-tizen#454]
I see many plugins but not the important one, the InApp Purchase, is there a plan for it ? or may be I didn't saw it ?

**Comment by swift-kim** [comment]
Official billing solutions for Tizen apps:

- [Samsung IAP](https://developer.samsung.com/galaxy-watch-iap/overview.html): For Galaxy Store (Galaxy Watch)
- [Samsung Checkout](https://developer.samsung.com/smarttv/develop/guides/samsung-checkout/samsung-checkout.html): For TV Seller Office (Smart TV)

They are available as [native library](https://developer.samsung.com/galaxy-watch-tizen/techdoc/tizen-extension-sdk-guide.html) and [.NET nuget package](https://www.nuget.org/packages/Tizen.NET.TV) respectively, so we will be possible to make them into C++ and C# plugins for Flutter apps. However, we don't yet have a plan to implement them. @flutter-tizen/maintainers Anybody interested?

**Comment by xuelian-bai** [comment]
do we need to implement a plugin for it? app can just call samsung checkout app, which has its own UI

**Comment by swift-kim** [comment]
@xuelian-bai Is there a way to open and interact with the app in Dart code?

**Comment by nassimus26** [comment]
> do we need to implement a plugin for it? app can just call samsung checkout app, which has its own UI

An inapp purchase plugin is aim to allow you to check if the user has a valid subscription or a valid purchase (purchase history) in plus to the purchase API

**Comment by xuelian-bai** [comment]
I will add this plugin in our development plan, and I will update details in this session soon

**Comment by swift-kim** [comment]
We may refer to the [**pay**](https://pub.dev/packages/pay) plugin when designing our plugin API. It's an unofficial open source package developed by Google developers.

**Comment by xuelian-bai** [comment]
[https://github.com/flutter-tizen/plugins/pull/562](url)

**Comment by Zartek-Technologies** [comment]
Any update on the IAP plugin implementation ?

**Comment by xuelian-bai** [comment]
> Any update on the IAP plugin implementation ?

Here is the PR for IAP https://github.com/flutter-tizen/plugins/pull/562, it will merge after review finished

**Comment by swift-kim** [comment]
Note that https://github.com/flutter-tizen/plugins/pull/562 is for the TV app store. No IAP plugin is planned for Galaxy Store (watch).

**Comment by xuelian-bai** [comment]
@nassimus26  @Zartek-Technologies IAP plugin https://github.com/flutter-tizen/plugins/pull/562  is merged, I will close this issue
