### ISSUE TITLE
Several Problems on TV platform

### ISSUE THREAD

**Issue by raynoryip** [flutter-tizen/flutter-tizen#455]
Hi Flutter Tizen Team,

**1) Cursor not showing**

I was creating a web app for Samsung M8, however, there is no cursor showing on the app even if the mouse is connected.
Here is my very simple architecture:
Main UI --> Display only one button, and this button is linked to url_launcher_tizen (Cursor not shown here)
url_launcher_tizen --> launches a browser with an url. (Cursor is shown here) 
May I know if this feature is not implemented or is it a bug. 

**2) Enter Key (from keyboard) not responding to the textfield onTap() or onFieldSubmitted() method**

I was trying to create a textfield to ask for user input, but the Enter key from the keyboard seems not responding to the submit feature.
(I could only use the "Go" button on the virtual keyboard to submit the request), do you  know if there is any other way for Flutter tizen to acquire user input other than TextFormfield?

Much appreciate your help.

**Comment by swift-kim** [comment]
cc @bbrto21 @JSUYA

**Comment by JSUYA** [comment]
Hi @raynoryip 
> 2) Enter Key (from keyboard) not responding to the textfield onTap() or onFieldSubmitted() method

When I tested using `TextField` and `onSubmitted()`, I checked that it works normally when I press Enter after inputting text with a physical keyboard.
Try using `TextField` and `onSubmitted()` ?

```dart
...
String _test = "TEST EnterKey";
...
children: <Widget>[
            Text(
              _test,
            ),
            TextField(
                onSubmitted: (text) {
                  setState(() {
                    _test = text;
                  });
                },
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Test',
                )),
          ],

```

**Comment by raynoryip** [comment]
> Hi @raynoryip
> 
> > 2. Enter Key (from keyboard) not responding to the textfield onTap() or onFieldSubmitted() method
> 
> When I tested using `TextField` and `onSubmitted()`, I checked that it works normally when I press Enter after inputting text with a physical keyboard. Try using `TextField` and `onSubmitted()` ?
> 
> ```dart
> ...
> String _test = "TEST EnterKey";
> ...
> children: <Widget>[
>             Text(
>               _test,
>             ),
>             TextField(
>                 onSubmitted: (text) {
>                   setState(() {
>                     _test = text;
>                   });
>                 },
>                 decoration: InputDecoration(
>                   border: OutlineInputBorder(),
>                   labelText: 'Test',
>                 )),
>           ],
> ```

Hi JSUYA, 

Thanks for the code, I think it works now!
But do you guys know about the cursor too? I still can't have my mouse cursor on any app I deploy on tizen...

**Comment by JSUYA** [comment]
Sorry for not being able to help you quickly.
When I tested on my TV device, the cursor was displayed normally.

1. Does not the cursor display in the newly created default app in the same way?
```
ex) flutter-tizen create test_app
      cd test_app
      flutter-tizen run
```

2. Can you check the log message?
command : `sdb dlog | grep Cursor`
if it's normal
```
I/VD_WIN_UTIL(23716): cursor_module.c: Cursor_Set_Config(1046) > config_type as 1
I/CURSORMGR(  268): e_mod_cursormgr.c: _e_cursormgr_cb_cursor_set_config(344) > Cursor_Set_Config request from client with process:23716 config[1] !
```
You could find these logs.
If you have any other error messages we can refer to, please share to us.

**Comment by raynoryip** [comment]
> Sorry for not being able to help you quickly. When I tested on my TV device, the cursor was displayed normally.
> 
> 1. Does not the cursor display in the newly created default app in the same way?
> 
> ```
> ex) flutter-tizen create test_app
>       cd test_app
>       flutter-tizen run
> ```
> 
> 2. Can you check the log message?
>    command : `sdb dlog | grep Cursor`
>    if it's normal
> 
> ```
> I/VD_WIN_UTIL(23716): cursor_module.c: Cursor_Set_Config(1046) > config_type as 1
> I/CURSORMGR(  268): e_mod_cursormgr.c: _e_cursormgr_cb_cursor_set_config(344) > Cursor_Set_Config request from client with process:23716 config[1] !
> ```
> 
> You could find these logs. If you have any other error messages we can refer to, please share to us.

Hi JSUYA, Sorry for not replying for a month, I had an urgent trip and just came back.

1) I created an app from your command, and no mouse cursor appears on screen:
![flutter_01](https://user-images.githubusercontent.com/60310807/204125842-3b762ddc-87c8-406b-ad78-823fd939d6fd.png)

**(I had both mouse and keyboard connected, and they works fine on the default browser app on TV)**


2) I tried to use `sdb dlog | grep Cursor` too, but nothing happened.
So I tried to use `sdb shell`, and i got:
```
closed
closed
```

**Comment by JSUYA** [comment]
Hi. Sorry for late reply

I've searched for a way around this but still haven't found the problem.
According to this code, Cursor_Set_Config() should be called when TV_Profile.
https://github.com/flutter-tizen/embedder/blob/c71260bb8b4cce9d63d0dc62ebe75f3b618c86df/flutter/shell/platform/tizen/tizen_window_ecore_wl2.cc#L125
If there is a problem, you can see an error message.

We currently do not have any M8 devices available for testing. 
Hi @yman-son  Do you know how to enable Mousr Cursor on M8 device? Do we need any other special logic?

@raynoryip 
On the screenshot, the app doesn't seem to be debug mode.
Could you please share all logs after `flutter-tizen run`?

@swift-kim Do you know any issues with the Mouse cursor?

**Comment by raynoryip** [comment]
> Hi. Sorry for late reply
> 
> I've searched for a way around this but still haven't found the problem. According to this code, Cursor_Set_Config() should be called when TV_Profile. https://github.com/flutter-tizen/embedder/blob/c71260bb8b4cce9d63d0dc62ebe75f3b618c86df/flutter/shell/platform/tizen/tizen_window_ecore_wl2.cc#L125 If there is a problem, you can see an error message.
> 
> We currently do not have any M8 devices available for testing. Hi @yman-son Do you know how to enable Mouse Cursor on M8 device? Do we need any other special logic?
> 
> @raynoryip On the screenshot, the app doesn't seem to be debug mode. Could you please share all logs after `flutter-tizen run`?
> 
> @swift-kim Do you know any issues with the Mouse cursor?

Hi JSUYA,

Somehow a rounded cursor showed up when I changed to a partner license....
Which is quite weird, so using other licenses blocked the display of the mouse cursor? 
And the cursor seems a bit different than the original one too: 
**（Sorry, inside screenshot doesn't show this cursor as well :()** 
![rsz_pxl_20221206_145414394](https://user-images.githubusercontent.com/60310807/205948303-22a24d35-faa0-4b0b-9722-2f230ada309d.jpg)
Original one:
**(Screenshot not supported for Tizen L3xxxxxxx)**
![rsz_2pxl_20221206_145809201](https://user-images.githubusercontent.com/60310807/205948589-30131507-e83a-4107-8431-474af63916c1.jpg)

And Do i have to download other packages to enable the sdb command?

**Comment by swift-kim** [comment]
Sdb commands (such as `shell` and `dlog`) are not supported on TV devices due to VD's security policies.

```sh
secure_protocol:enabled
```

**Comment by JSUYA** [comment]
> Sdb commands (such as `shell` and `dlog`) are not supported on TV devices due to VD's security policies.

As in this comment, shell access is not supported in release binaries for security reasons. (intershell_support:disabled)

> Somehow a rounded cursor showed up when I changed to a partner license....

It is correct that a rounded cursor is showed up. (currently...)

> Which is quite weird, so using other licenses blocked the display of the mouse cursor?

I'm glad your problem has resolved(?). I've been looking to see if the license(partner) has anything to do with this problem, but I haven't been able to find it yet.

**Comment by swift-kim** [comment]
So... is using the partner-level certificate the final solution?
