### ISSUE TITLE
Connecting to the device logger is taking longer than expected... (Tizen 6.0 and 6.5)

### ISSUE THREAD

**Issue by mhoeckner** [flutter-tizen/flutter-tizen#480]
Dear Dev Team,

actually we are not able to install new builds on our TVs
Confirmed on different TVs (6.0 and 6.5) and different build machines (Windows and MacOS)

Error:

Connecting to the device logger is taking longer than expected...
Still attempting to connect to the device logger...
If you do not see the application running on the device, it might have crashed. The device log (dlog) might have more details.
Please open an issue in https://github.com/flutter-tizen/flutter-tizen/issues if the problem persists.

We also created a new Samsung Cert via Certificate Manager. Public and Partner Level. No changes. Only emulator works at the moment.

Can you please help us with this? What is the problem?

Thank you in advance,
regards
Markus

flutter-tizen doctor -v output:

[!] Flutter (Channel unknown, 3.3.7, on macOS 13.0.1 22A400 darwin-x64, locale en-AT)
    ! Flutter version 3.3.7 on channel unknown at /Users/markushockner/development/flutter-tizen/flutter
    ! Upstream repository unknown
    • Framework revision e99c9c7cd9 (3 months ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Tizen toolchain - develop for Tizen devices
    • Framework revision 81c0992ea7 (3 weeks ago), 2023-01-16 10:43:40 +0900
    • Engine revision 2874fe8bdda2814a59244f329f331e35f73e46d9
    • Tizen Studio 4.6 at /Users/markushockner/tizen-studio
    • .NET SDK 6.0.403 at /usr/local/share/dotnet/dotnet

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/markushockner/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/markushockner/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/local/bin/chrome_unsafe

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • macOS (desktop)               • macos             • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)                  • chrome            • web-javascript • Google Chrome 109.0.5414.119
    • Tizen GU50AU8079UXZG (mobile) • 172.16.66.3:26101 • flutter-tester • Tizen 6.0

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by swift-kim** [comment]
Hi.

Apparently the app has failed to launch for some unknown reason. The problem is usually caused by plugins the app is dependent on. Could you list the dependencies if the app has any? Can you launch a simple app just created with the `flutter-tizen create --platforms tizen my_app` command?

**Comment by mhoeckner** [comment]
Hi

Test app works

We have not changed our dependencies since mid january

What we tried:
- older build of our app
- older samsung tizen version (3.3.0)
- updated tizen studio
- changed certificate
- cleared pub cache
- reset tv(s)

Nothing helped.

But then - all of the sudden - it worked. Hmmm....

So we made further investigation. Problem seems to be the build for Emulator. We could reproduce the error. 
- start emulator
- flutter-tizen run for emulator 
- flutter-tizen run on tv  
=> error

- flutter-tizen clean
- flutter-tizen pub get clean
- flutter-tizen pub get
- flutter-tizen run on tv 
=> works

It seems that the build for emulator could not be started on tv -> a simple rebuild of the app uses the cache pre build for emulator. Maybe someone got this issue in future ^^

Thanks @swift-kim  for support
