### ISSUE TITLE
Hot to detect if the app is running on tizen ?

### ISSUE THREAD

**Issue by nassimus26** [flutter-tizen/flutter-tizen#482]
Flutter offers the Platform class to check on which platform the app is running, but how to check if we are running on Tizen Platform ?

**Comment by nassimus26** [comment]
This should do the job for me !(Platform.isWindows || Platform.isAndroid || Platform.isMacOS) , I have no plan to publish anywhere else so it's sufficient

**Comment by swift-kim** [comment]
The official way to check if the current running platform is Tizen is to use the [`isTizen`](https://pub.dev/documentation/flutter_tizen/latest/flutter_tizen/isTizen.html) property of the `flutter_tizen` package as documented in https://github.com/flutter-tizen/flutter-tizen/wiki/Limitations#apis, but you can just copy its implementation and inline into your code if you don't want to add the package dependency just for that.

**Comment by nassimus26** [comment]
Thank you @swift-kim  for the quick reply, very kind !
