### ISSUE TITLE
error: in video_player

### ISSUE THREAD

**Issue by goliveok** [flutter-tizen/flutter-tizen#483]
hi all

i have problem in my app .

i need create app for streaming live m3u8 and mp2t my source is good in android video_player

in flutter-tizen and video_player not working my stream screen loading and not open image.

plz help me.

**Comment by mhoeckner** [comment]
Hi

have you tried video_player_videohole
Should be merged in main soon

https://github.com/flutter-tizen/plugins/tree/video_player_videohole

regards
Markus

**Comment by xuelian-bai** [comment]
yes, Markus is right, please try video_player_videohole plugin, if there is still issue, please let us know your test stream

**Comment by xuelian-bai** [comment]
@goliveok can you run video_player sample in flutter-tizen properly? which device did you use for test?
