### ISSUE TITLE
Flutter App rejected for TTS issue

### ISSUE THREAD

**Issue by nassimus26** [flutter-tizen/flutter-tizen#487]
My flutter app has been rejected for an issue about TTS that I don't understand, 

Here the defect report : 

```
TTS works in the app
Expected Result
If the app supports TTS, you need to update the information on the app's details page. Otherwise, you need to turn off the TTS in the app.
Procedure
0. On app info page says TTS 'No Data'
1. Activate TTS
2. Open the app
3. Move through the App
Notice defect: TTS works in the app
```
My app dosn't support TTS (text to speech), so what I have to do about this ? they said I have to turn off TTS in the App but my app dosn't support TTS at all

**Comment by nassimus26** [comment]
Refering to this post
https://stackoverflow.com/questions/60446632/how-to-disable-text-to-speech-using-javascript

I added this to my `tizen-manifest.xml`

` <metadata key="http://samsung.com/tv/metadata/use.voiceguide" value="false" />`

**Comment by swift-kim** [comment]
Did you uncheck "TTS (Text to Speech)" in the "App Features Info" page before submitting your app?

If it's the [Screen Reader](https://docs.flutter.dev/development/accessibility-and-localization/accessibility#screen-readers) accessibility feature that they mean by the term "TTS", it should normally work in your app even if you haven't configured explicitly. You may ask what they're exactly referring to and what kind of information should be filled in the app's details page by creating a 1:1 Q&A ticket in https://seller.samsungapps.com/tv/qna.

**Comment by nassimus26** [comment]
Yes, I never select TTS feature

**Comment by xuelian-bai** [comment]
https://developer.samsung.com/smarttv/develop/guides/fundamentals/configuring-tv-applications.html

**Comment by swift-kim** [comment]
https://developer.samsung.com/smarttv/develop/guides/fundamentals/text-to-speech.html

Text to Speech means Voice Guide in their terminology.

The feature is not supported on TV emulator. You need a real TV to test the feature. If you don't have one, well, you don't have to test the feature and can just assume the feature works perfectly within your app.

**Comment by nassimus26** [comment]
@swift-kim @xuelian-bai thank you for the clarification, I submit a new version with 

`<metadata key="http://samsung.com/tv/metadata/use.voiceguide" value="false" />`

It should do the job, I just need to disable it as they want

**Comment by swift-kim** [comment]
I don't think that metadata will work with Flutter apps. Therefore the result will be the same.

As I explained above, TTS should work automatically in Flutter apps even if you haven't configured it manually. I don't know if there is a way to explicitly disable it, but even if there is, you should only do so if you really want to prevent visually impaired users from using your app.

**Comment by nassimus26** [comment]
@swift-kim so what you are suggesting ? Enabling the TTS without changing anything in the App should do the job ?

**Comment by swift-kim** [comment]
Yes, you can simply indicate that your app supports TTS in the app info page. However, it is highly recommended to test the feature thoroughly on a real TV before submitting the app.

**Comment by nassimus26** [comment]
@swift-kim i don’t want to support TTS ( I don’t care about it €, I just want them to validate the app like it is, and I don’t have a Samsung TV anyway

**Comment by swift-kim** [comment]
Then please leave your comments in the "App Description File" or open a 1:1 Q&A ticket in the store website. We're not affiliated with the TV store team or the Samsung TV division. We can't help with non-technical issues.

**Comment by nassimus26** [comment]
Thank you @swift-kim , I know you are doing your best to help, but I am just saying the truth, I don’t need TTS , it was already a long journey to adapt the app like it is

**Comment by swift-kim** [comment]
The information I provided above should be enough. Please be specific if you need more help.

**Comment by swift-kim** [comment]
Closing the issue. Please reopen if you need further assistance.
