### ISSUE TITLE
Regarding `defaultTargetPlatform`

### ISSUE THREAD

**Issue by daeyeon** [flutter-tizen/flutter-tizen#489]
When you need to branch based on the platform Flutter is currently running on, is there a way to distinguish between `linux` and `tizen`? For example, FlutterFire guides the code below as an example about setting up their option. And I observed that the [defaultTargetPlatform](https://api.flutter.dev/flutter/foundation/defaultTargetPlatform.html) is `linux` on the Tizen platform.
```dart
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux: // <-
        return linux;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }
}
```

**Comment by swift-kim** [comment]
Possible duplicate of https://github.com/flutter-tizen/flutter-tizen/issues/482?

**Comment by daeyeon** [comment]
Not exactly. Is it tricky to support defaultTargetPlatform?

**Comment by swift-kim** [comment]
Tizen is one of Linux distributions, and as a result the `defaultTargetPlatform` property reports `TargetPlatform.linux` on Tizen. Changing the behavior will require a modification to the framework itself.

Do you have a specific requirement?

**Comment by daeyeon** [comment]
`TargetPlatform.linux` is interpreted as linux desktop, not linux kernel-based. It's also distinct in the CLI tool option, '--platforms=android,linux,tizen'.

Not a strictly necessary constraint. Curious about its feasibility since it seemingly makes more sense.

**Comment by swift-kim** [comment]
Yes, adding the constant to the framework will make more sense for general users, but doing so will require an approval from the Flutter team. I thought it was unlikely that they would accept such change (adding the constant means adding a new officially supported platform to Flutter), so I just documented an alternative solution in the wiki.

**Comment by daeyeon** [comment]
Thanks for the clarification. Will use the alternative.
