### ISSUE TITLE
Video Player 4K Error 

### ISSUE THREAD

**Issue by phyochan** [flutter-tizen/flutter-tizen#491]
Can not Play 4K in real Device. How to fix it ?. My Smart Monitor is 4K support

**Comment by xuelian-bai** [comment]
hi, please let me know your device info(Menu->Support-> About TV->Software version) and error log.

**Comment by phyochan** [comment]
Hello sorry for late. My Smart monitor is m8 . When 4k video freeze and slow. Latest Tizen video player plugin is using
