### ISSUE TITLE
Sending the application to the TV

### ISSUE THREAD

**Issue by tahayasinkoksal** [flutter-tizen/flutter-tizen#496]
I follow the steps at this address, but somehow I could not send the application to my TV.
URL: https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/get-started.md

1)I created the app
`
$ flutter-tizen create myapp
$ cd myapp
`
2)I am sending the application.
`flutter-tizen run`

**Output in terminal:**

**Taha-MacBook-Pro:myapp tahayasinkoksal$ flutter-tizen run**
Launching tizen/flutter/generated_main.dart on Tizen UE75BU8000UXTK in debug mode...
The ttt profile is used for signing.
Building a Tizen application in debug mode...                      16,7s
✓ Built build/tizen/tpk/com.example.myapp-1.0.0.tpk (23.5MB).
Installing build/tizen/tpk/com.example.myapp-1.0.0.tpk...          32,4s
Installing TPK failed:
WARNING: Your data are to be sent over an unencrypted connection and could be read by others.
pushed    com.example.myapp-1.0.0.tpk	  0%	      0MB	    0KB/spushed    com.example.myapp-1.0.0.tpk	  7%	      1MB
1509KB/spushed    com.example.myapp-1.0.0.tpk	 11%	      2MB	  947KB/spushed    com.example.myapp-1.0.0.tpk	 15%	      3MB
957KB/spushed    com.example.myapp-1.0.0.tpk	 19%	      4MB	  914KB/spushed    com.example.myapp-1.0.0.tpk	 22%	      5MB
896KB/spushed    com.example.myapp-1.0.0.tpk	 27%	      6MB	  907KB/spushed    com.example.myapp-1.0.0.tpk	 30%	      7MB
856KB/spushed    com.example.myapp-1.0.0.tpk	 34%	      8MB	  856KB/spushed    com.example.myapp-1.0.0.tpk	 36%	      8MB
543KB/spushed    com.example.myapp-1.0.0.tpk	 38%	      9MB	  659KB/spushed    com.example.myapp-1.0.0.tpk	 43%	     10MB
863KB/spushed    com.example.myapp-1.0.0.tpk	 46%	     10MB	  884KB/spushed    com.example.myapp-1.0.0.tpk	 50%	     11MB
911KB/spushed    com.example.myapp-1.0.0.tpk	 53%	     12MB	  920KB/spushed    com.example.myapp-1.0.0.tpk	 57%	     13MB
857KB/spushed    com.example.myapp-1.0.0.tpk	 61%	     14MB	  895KB/spushed    com.example.myapp-1.0.0.tpk	 65%	     15MB
904KB/spushed    com.example.myapp-1.0.0.tpk	 68%	     16MB	  918KB/spushed    com.example.myapp-1.0.0.tpk	 72%	     17MB
897KB/spushed    com.example.myapp-1.0.0.tpk	 75%	     17MB	  862KB/spushed    com.example.myapp-1.0.0.tpk	 80%	     18MB
881KB/spushed    com.example.myapp-1.0.0.tpk	 83%	     19MB	  902KB/spushed    com.example.myapp-1.0.0.tpk	 87%	     20MB
843KB/spushed    com.example.myapp-1.0.0.tpk	 90%	     21MB	  865KB/spushed    com.example.myapp-1.0.0.tpk	 94%	     22MB
932KB/spushed    com.example.myapp-1.0.0.tpk	 97%	     23MB	  887KB/spushed    com.example.myapp-1.0.0.tpk	100%	     23MB
887KB/s
1 file(s) pushed. 0 file(s) skipped.
/Users/tahayasinkoksal/Desktop/tvAppDeneme/myapp/build/tizen/tpk/com.example.myapp-1.0.0.tpk   869KB/s (24689734 bytes in
27.717s)

install com.example.myapp
package_path /home/owner/share/tmp/sdk_tools/com.example.myapp-1.0.0.tpk
app_id[com.example.myapp] install start
app_id[com.example.myapp] installing[10]
app_id[com.example.myapp] installing[13]
app_id[com.example.myapp] installing[16]
app_id[com.example.myapp] installing[18]
app_id[com.example.myapp] installing[21]
app_id[com.example.myapp] installing[24]
app_id[com.example.myapp] installing[27]
app_id[com.example.myapp] install failed[118, -12], reason: Check certificate error : 
spend time for wascmd is [4428]ms
Error launching application on Tizen UE75BU8000UXTK.
**(base) Taha-MacBook-Pro:myapp tahayasinkoksal$**

**Comment by swift-kim** [comment]
Hi. Did you create and activate a "Samsung" certificate profile in Certificate Manager? The device must be connected to your PC when you create a distributor certificate.

**Comment by tahayasinkoksal** [comment]
> Hi. Did you create and activate a "Samsung" certificate profile in Certificate Manager? The device must be connected to your PC when you create a distributor certificate.

Thanks for the answer but I created it before and it looks like this. Did I create it wrong?
I'm using Apple M1, could it be a problem with the computer?
<img width="700" src="https://i.ibb.co/tCt6kvK/Ekran-Resmi-2023-05-16-11-22-04.png">

**Comment by swift-kim** [comment]
Hmm. I'm not sure how you created the certificate profile but it looks like something went wrong. The verifier part ("Verified by" in the screenshot) of the author certificate should be either Tizen or Samsung, but not your name. Please make sure you have installed the "Samsung Certificate Extension" in Package Manager and follow the steps in [Creating Certificates](https://developer.samsung.com/smarttv/develop/getting-started/setting-up-sdk/creating-certificates.html) to create a valid Samsung certificate profile. Use the "Public" level privilege unless you are a registered partner.
