### ISSUE TITLE
Use native shared libs and headers provided by other plugins

### ISSUE THREAD

**Issue by daeyeon** [flutter-tizen/flutter-tizen#500]
This is a feature request regarding plugin builds.

### What is the problem?

In the example below, `db_plugin` needs to use 'common.so' and 'common.h' to be built. And the same 'common.so' and 'common.h' can be found in `core_plugin`. The problem is that when building `db_plugin`, the library and the header provided by `core_plugin` are not available, so `db_plugin` has to store them redundantly.

#### Example: directory structure and files.
```
core_plugin (plugin)
  - tizen/inc
    * common.h
  - tizen/lib/armel,i586
    * common.so

db_plugin (plugin)
  - tizen/inc
    * common.h
    * db.h
  - tizen/lib/armel,i586
    * common.so
    * db.so

test (app)
```

```yaml
# pubspec.yaml
name: test
...
dependencies:
  core_plugin:
  db_plugin:
```

### What is the feature proposed to solve the problem?

Provide a way to utilize native shared libs and headers provided by other plugins in the build time. Here is my idea: provide a specific path like `FLUTTER_INTERMEDIATE_*_DIR`, and allow each plugin to copy headers and libraries to the path through the pre-build command [before building the whole plugins](https://github.com/flutter-tizen/flutter-tizen/blob/80d3e675aed3533fbf244a9de79c0c56aad95d26/lib/build_targets/plugins.dart#L119).

```make
# build_def.prop
PREBUILD_COMMAND=<rsync headers and libs to FLUTTER_INTERMEDIATE_*_DIR>
```

```make
# project_def.prop
USER_INC_DIRS = inc src ${FLUTTER_INTERMEDIATE_INC_DIR}
USER_INC_FILES =
USER_CPP_INC_FILES =

USER_LIBS = common db
USER_LIB_DIRS = lib/${BUILD_ARCH} ${FLUTTER_INTERMEDIATE_LIBS_DIR}/${BUILD_ARCH}
```

**Comment by daeyeon** [comment]
Even with staticLib, `common.h` in the `core_plugin` cannot be used for building `db_plugin`, which means that a duplicated copy of the header needs to be stored in `db_plugin` still. Is my understanding correct?

**Comment by swift-kim** [comment]
Technically you shouldn't even need the header but that's not what we need to decide right now. I just want you to test if it works.

**Comment by daeyeon** [comment]
Yes, I confirmed switching to `staticLib` works as well.

**Comment by swift-kim** [comment]
So we could either use the `staticLib` approach for simplicity, or the current structure (duplicate files) or your approach for explicity. I'm not sure how the `PREBUILD_COMMAND` (which is part of a plugin build) can be executed before building all plugins in your approach.

There are a few other things to discuss so let's have an offline meeting.
