### ISSUE TITLE
[TV] Prevent screensaver 

### ISSUE THREAD

**Issue by lKinderBueno** [flutter-tizen/flutter-tizen#504]
I noticed the TV screensaver appears after 2 minutes from the last user interaction. The problem is I am developing a TV player and the app content should not be hidden and there is no static image. 
The wakelock plugin is not compatible with TV and I can't figure out any workaround to prevent that. 
Is it an issue with futter tizen?

**Comment by swift-kim** [comment]
> I noticed the TV screensaver appears after 2 minutes from the last user interaction.

It's 2 "hours" but not 2 minutes on my TV and there's no way to change the value unless I turn the feature off completely. Is it not the case for you?

**Comment by xuelian-bai** [comment]
Normally screensaver will be enabled when playback status is Pause or Stop and no keyinput for some time(2 hours). If player is playing, scrensaver is supposed to be disabled. (Ref: https://developer.samsung.com/smarttv/develop/guides/fundamentals/setting-screensaver.html)
For your case, which player plugin do you use? When screen saver appear, is the player in playing status?

**Comment by lKinderBueno** [comment]
> > I noticed the TV screensaver appears after 2 minutes from the last user interaction.
> 
> It's 2 "hours" but not 2 minutes on my TV and there's no way to change the value unless I turn the feature off completely. Is it not the case for you?

In my case it is 2 minutes, probably because it is a monitor (Samsung g8 oled) and/or an oled display.
The screensaver does not show if I use other application as Netflix. 

> Normally screensaver will be enabled when playback status is Pause or Stop and no keyinput for some time(2 hours). If player is playing, scrensaver is supposed to be disabled. (Ref: https://developer.samsung.com/smarttv/develop/guides/fundamentals/setting-screensaver.html) For your case, which player plugin do you use? When screen saver appear, is the player in playing status? Please also let me know your software version: Menu->Support-> About this TV --> Software Version

I am using video_player and video_player_tizen. I tried with a demo project containing only the code from the video_player example ( [](https://pub.dev/packages/video_player)) and if I play the video after two minutes it appears the screensaver and the video continue to play in the background. It happens also if I install the tpk file and open it through the "App" page.  On other applications such as Netflix the screensaver does not appear, I think there is some setting to enable.

I opened a ticket on the samsung seller portal asking if there is a way to disable the screensaver with .NET. The AppCommon module is only for webapi, but there is no reference in the documentation on how to use it for .NET.
They wrote me this:
ElmSharp module is the one that should resolve your issue. As the description says, there is possibility to switch the mode on "Always On" which keep screen turned on - for more info check this link - 
[https://developer.tizen.org/dev-guide/csapi/api/ElmSharp.ScreenMode.html](https://developer.tizen.org/dev-guide/csapi/api/ElmSharp.ScreenMode.html)

I haven't yet tested if this solution may solve the issue because I am on vacation till Monday. 
I am using a smart monitor, a Samsung G8 oled, the latest firmware update is 1504.0 I'll provide you more details about the tv/monitor firmware version once I am back

**Comment by xuelian-bai** [comment]
I think you can try to use https://github.com/flutter-tizen/plugins/tree/master/packages/video_player_videohole for now, it use tizen native player which will disable screensaver inside player. 
For this plugin https://pub.dev/packages/video_player, we will try to fix this issue.

**Comment by swift-kim** [comment]
Otherwise we should make `wakelock_tizen` work for TV devices as well or create a new Dart API for disabling the screensaver. We need to investigate further.

FYI) My TV is also a monitor (M5) but it looks like not all monitors have the same default timeout.

**Comment by xuelian-bai** [comment]
> FYI) My TV is also a monitor (M5) but it looks like not all monitors have the same default timeout.
yes, I checked a Samsung G8 oled game monitor, the default timeout is 2 minutes, it's different from other TV devices

**Comment by lKinderBueno** [comment]
> I think you can try to use https://github.com/flutter-tizen/plugins/tree/master/packages/video_player_videohole for now, it use tizen native player which will disable screensaver inside player. For this plugin https://pub.dev/packages/video_player, we will try to fix this issue.

Thanks. With video_player_videohole the screensaver does not appear, so at least for me this is a valid solution.
