### ISSUE TITLE
Unable to build due to Exception: The rootstrap wearable-4.0-device.core could not be found

### ISSUE THREAD

**Issue by beingentangled** [flutter-tizen/flutter-tizen#505]
[   +6 ms] Exception: The rootstrap wearable-4.0-device.core could not be found.
           To install missing package(s), run:
           /Users/---/tizen-studio/package-manager/package-manager-cli.bin install WEARABLE-4.0-NativeAppDevelopment-CLI

When trying to install: 

 /Users/---/tizen-studio/package-manager/package-manager-cli.bin install WEARABLE-4.0-NativeAppDevelopment-CLI                                                                             ─╯

Package Manager (0.5.39)

****************************************
******* Start to update packages *******
****************************************
Nothing to update.

****************************************
****** Start to install packages *******
****************************************
Nothing to install.

Exception: Failed to build C++ embedding:

**Comment by swift-kim** [comment]
Hmm. This is very unexpected. Does the directory `tizen-studio/platforms/tizen-4.0/wearable/rootstraps/wearable-4.0-device.core` exist? Would you try uninstalling and reinstalling the package? (by using the GUI Package Manager or simply replacing `install` with `uninstall` in the command)

**Comment by Stuggy** [comment]
I am getting the same error.  I am actually trying to target 5.5 since my watch is on that version.

**Comment by swift-kim** [comment]
@Stuggy Actually Tizen 5.5 is now the minimum supported version and is the default. Did you run the `package-manager-cli` command as prompted?

**Comment by Stuggy** [comment]
I think I worked out where to signal to use 5.5.  I think it was in the manifest I believe.  I only have  wearable 5.5 installed from the Tizen package manager so I believe that for me this issue is resolved.

**Comment by swift-kim** [comment]
@Stuggy Yes, you can change the target API version of your app in its `tizen-manifest.xml` file.

Closing because there's no response from the author.
