### ISSUE TITLE
App Crashes when launch on TV

### ISSUE THREAD

**Issue by aramikg** [flutter-tizen/flutter-tizen#512]
I have a Samsung 85" QA900A.

In the emulator my app works just fine, but when I launch it on my actual TV it crashes on launch.  I'm using the cert that has the TV on there.  The Samsung cert not the Tizen cert.  

Has anyone run into this issue?

It says if problem continues check the dlog, but I don't see any logs anywhere... 

```
Connecting to the device logger is taking longer than expected...
Still attempting to connect to the device logger...
If you do not see the application running on the device, it might have crashed. The device log (dlog) might have more
details.
``.

I see the app on my TV but a spinner comes up then goes away any then nothing else happens.  

Anyone else having this issue?

**Comment by swift-kim** [comment]
Hmm. What exactly is the model name? I can't find QA900A on Google.

**Comment by aramikg** [comment]
> Hmm. What exactly is the model name? I can't find QA900A on Google.

Yea I had trouble with that as well but my receipt has it listed as 

'85” Class QN900A Samsung Neo QLED 8K Smart TV (2021) - NextGen TV QN85QN900AFXZA'

**Comment by swift-kim** [comment]
The model is not listed in https://developer.samsung.com/smarttv/develop/specifications/tv-model-groups.html. Could you run `sdb capability` to check if the device is running Tizen 6.0 OS?

```
$ sdb capability
...
device_name:Tizen
platform_version:6.0
...
```

**Comment by xuelian-bai** [comment]
This model is 2021 8K oscarP

**Comment by swift-kim** [comment]
If the TV is running Tizen 6.0, I have no idea what's preventing the app from launching. Could you provide detailed reproduction steps or send us your TPK?

**Comment by herodotpiotr** [comment]
mam ten sam problem od piątku wcześniej aplikacja się uruchamiała na moim testowym TV

**Comment by herodotpiotr** [comment]
I've had the same problem since Friday before, the app would launch on my test TV

**Comment by xuelian-bai** [comment]
@aramikg @herodotpiotr please share following info:
1. flutter-tizen doctor -v
2. menu->support->about this TV->Software version
3. Which sample on github flutter-tizen crashed?

We tested on OscarP model yesterday, our sample app could be launched successfully

**Comment by fioleta72** [comment]
@swift-kim
is the same in my case. The strange is flutter-tizen run --profile work fine

**Comment by fioleta72** [comment]
flutter-tizen doctor -v
[!] Flutter (Channel [user-branch], 3.13.1, on macOS 14.0 23A344 darwin-arm64, locale en-VE)
    ! Flutter version 3.13.1 on channel [user-branch] at /Users/fioleta/flutter-tizen/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision e1e47221e8 (3 months ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Tizen toolchain - develop for Tizen devices
    • Framework revision 7bb72513aa (9 weeks ago), 2023-09-27 18:51:23 +0900
    • Engine revision 063c88536e
    • Embedder revision 20e00fdfc0
    • Tizen Studio 5.5 at /Users/fioleta/tizen-studio
    • .NET SDK 7.0.402 at /usr/local/share/dotnet/dotnet

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/fioleta/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/fioleta/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)
    • macOS (desktop)               • macos                 • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                  • chrome                • web-javascript • Google Chrome 119.0.6045.159
    • Tizen UE55CU7192UXXH (mobile) • 192.168.100.156:26101 • flutter-tester • Tizen 7.0

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

-----------------------------

my test device: UE55CU7192UXXH

All was work before a week... now no
