### ISSUE TITLE
Can Flutter Tizen use .NET plugins from the Tizen SDK?

### ISSUE THREAD

**Issue by ljhtswhudxb3823** [flutter-tizen/flutter-tizen#517]
I want to use some Tizen native APIs, such as Account, in the Dart code of a Flutter Tizen project. Can I directly reference these APIs in Dart, and if so, how should I use them?

**Comment by ljhtswhudxb3823** [comment]
In the Flutter Tizen SDK, the APIs exist in the form of DLLs. Can Dart access these APIs?

**Comment by xuelian-bai** [comment]
Please check this: https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/develop-plugin-csharp.md
which plugin do you need? Sso?

**Comment by ljhtswhudxb3823** [comment]
If I want to reference the APIs provided by TizenFX, can I use them? Or, does flutter-tizen support interaction between Dart and C, such as through FFI?

**Comment by xuelian-bai** [comment]
hmm. Please check this for native apis https://github.com/flutter-tizen/tizen_interop 
For C# plugin, please check this: https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/develop-plugin-csharp.md
FFI is supported

**Comment by ljhtswhudxb3823** [comment]
And how are native APIs provided to Dart, are they defined in the source code of the Tizen Engine?

**Comment by swift-kim** [comment]
For doing simple things like getting a string, the recommended way is to use https://github.com/flutter-tizen/tizen_interop.

If you need to implement a complex logic or reuse the same native code across multiple codebases, you may want to write it as a plugin (in either [C++](https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/develop-plugin.md) or [C#](https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/develop-plugin-csharp.md)) and use platform channels to communicate between Dart and C++/C#.

**Comment by ljhtswhudxb3823** [comment]
Is it like using the platform channel for dart to call the android native API? Thank you for your answer.

**Comment by swift-kim** [comment]
Yes, the exact same technologies used on other platforms are available on Tizen. The only difference is that unlike Android where Java is the only (primary) API language, you have two options (C and C#) to write native code for Tizen. Note that all our official [plugins](https://github.com/flutter-tizen/plugins) are written in C/C++, not C#. The C# plugin development is an experimental feature.
