### ISSUE TITLE
Facing the issue when trying to build tizen app

### ISSUE THREAD

**Issue by Rahil-Griphhy** [flutter-tizen/flutter-tizen#529]
rahilgriphhy@Rahils-Mac-mini vinipi_tv_system % flutter-tizen build tpk --device-profile tv 

Resolving dependencies... (5.7s)
  _flutterfire_internals 1.3.16 (1.3.19 available)
> collection 1.18.0 (was 1.17.2)
  csslib 0.17.3 (1.0.0 available)
  ffi 2.1.0 (2.1.2 available)
  firebase_core 2.24.2 (2.25.2 available)
  firebase_core_web 2.10.0 (2.11.2 available)
  firebase_messaging 14.7.10 (14.7.13 available)
  firebase_messaging_platform_interface 4.5.18 (4.5.21 available)
  firebase_messaging_web 3.5.18 (3.6.2 available)
  flutter_widget_from_html_core 0.8.5+3 (0.14.11 available)
  fwfh_text_style 2.22.8+3 (from dev dependency to transitive dependency) (2.23.8 available)
  http 0.13.6 (1.2.0 available)
  js 0.6.7 (0.7.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
> meta 1.10.0 (was 1.9.1) (1.11.0 available)
  network_info_plus 3.0.5 (4.1.0+1 available)
  path 1.8.3 (1.9.0 available)
  petitparser 5.4.0 (6.0.2 available)
  pointer_interceptor 0.9.3+7 (0.10.1 available)
> stack_trace 1.11.1 (was 1.11.0)
> stream_channel 2.1.2 (was 2.1.1)
> test_api 0.6.1 (was 0.6.0) (0.7.0 available)
  uuid 3.0.7 (4.3.3 available)
  video_player_avfoundation 2.5.2 (2.5.6 available)
  visibility_detector 0.3.3 (0.4.0+2 available)
> web 0.3.0 (was 0.1.4-beta) (0.4.2 available)
  webview_flutter 2.8.0 (4.5.0 available)
  webview_flutter_android 2.10.4 (3.14.0 available)
  webview_flutter_platform_interface 1.9.5 (2.10.0 available)
  webview_flutter_wkwebview 2.9.5 (3.11.0 available)
  win32 3.1.4 (5.2.0 available)
  xml 6.3.0 (6.5.0 available)
Changed 7 dependencies!
30 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

../../../../../.pub-cache/hosted/pub.dev/fwfh_text_style-2.22.8+3/lib/fwfh_text_style.dart:256:21: Error: The method '_TextStyleProxy.getParagraphStyle' doesn't have the named parameter 'textScaler' of overridden method
'TextStyle.getParagraphStyle'.
  ui.ParagraphStyle getParagraphStyle({
                    ^
../../../../../flutter-tizen/flutter/packages/flutter/lib/src/painting/text_style.dart:1328:21: Context: This is the overridden method ('getParagraphStyle').
  ui.ParagraphStyle getParagraphStyle({
                    ^
../../../../../.pub-cache/hosted/pub.dev/fwfh_text_style-2.22.8+3/lib/fwfh_text_style.dart:288:16: Error: The method '_TextStyleProxy.getTextStyle' has fewer named arguments than those of overridden method
'TextStyle.getTextStyle'.
  ui.TextStyle getTextStyle({double textScaleFactor = 1.0}) =>
               ^
../../../../../flutter-tizen/flutter/packages/flutter/lib/src/painting/text_style.dart:1273:16: Context: This is the overridden method ('getTextStyle').
  ui.TextStyle getTextStyle({
               ^
../../../../../.pub-cache/hosted/pub.dev/fwfh_text_style-2.22.8+3/lib/fwfh_text_style.dart:274:9: Error: No named parameter with the name 'textScaleFactor'.
        textScaleFactor: textScaleFactor,
        ^^^^^^^^^^^^^^^
target: kernel_snapshot
exception:Exception
#0      TizenKernelSnapshot.build (package:flutter_tizen/build_targets/application.dart:96:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#9      TizenBuilder.buildTpk (package:flutter_tizen/tizen_builder.dart:103:11)
<asynchronous suspension>
#10     BuildTpkCommand.runCommand (package:flutter_tizen/commands/build.dart:86:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tizen/executable.dart:84:3)
<asynchronous suspension>

Building a Tizen application in release mode...                    10.9s
The build failed.
rahilgriphhy@Rahils-Mac-mini vinipi_tv_system %

**Comment by Rahil-Griphhy** [comment]
@swift-kim can you please check this out?

**Comment by swift-kim** [comment]
Not sure but isn't it an issue with the wfh_text_style package?

**Comment by Rahil-Griphhy** [comment]
@swift-kim nop

i used this tizen packages
  network_info_plus_tizen:
  path_provider_tizen:
  wakelock_tizen:
  
  i faced this issue when build app with the help of tizen cmd.

**Comment by swift-kim** [comment]
I created an empty project and added the three packages as dependencies. No error detected.

https://pub.dev/packages/fwfh_text_style/changelog

The fwfh_text_style packages has an update (2.23.8) for the [new Flutter API](https://docs.flutter.dev/release/breaking-changes/deprecate-textscalefactor). You have to upgrade the package to the version by running `flutter-tizen pub upgrade`. That should fix your problem.
