### ISSUE TITLE
Unable to get pub meta >= 1.10.0

### ISSUE THREAD

**Issue by phuocbitmark** [flutter-tizen/flutter-tizen#533]
Hi,
When i tried to add [bonsoir](https://pub.dev/packages/bonsoir) into my tizen project, it returns this error:
///
Because bonsoir_platform_interface 5.1.2 depends on meta ^1.10.0 and no versions of bonsoir_platform_interface match >5.1.2 <6.0.0, bonsoir_platform_interface ^5.1.2 requires meta ^1.10.0.
And because every version of flutter from sdk depends on meta 1.9.1, flutter from sdk is incompatible with bonsoir_platform_interface ^5.1.2.
And because bonsoir 5.1.8 depends on bonsoir_platform_interface ^5.1.2 and no versions of bonsoir match >5.1.8 <6.0.0, flutter from sdk is incompatible with bonsoir ^5.1.8.
So, because feralfile_app_canvas_tizen depends on both flutter from sdk and bonsoir ^5.1.8, version solving failed.
///
turn out meta version in my flutter-tizen project is 1.9.1, while other flutter projects of mine, meta version is 1.11.0
I don't directly import meta, it gets meta library through flutter sdk

My question is: is that an issue of flutter-tizen, and how can i resolve it?

**Comment by phuocbitmark** [comment]
update:
I tried to change some pub version and dependencies are resolved
But the bonsoir code still not work.
I wonder does Tizen API support mDNS or just the pub has not implemented it

**Comment by JSUYA** [comment]
Hi. thank you for your interest.
[Bonsoir](https://github.com/Skyost/Bonsoir/tree/master/packages/bonsoir) doesn't support the Tizen platform.
A Tizen implementation is needed, but we have no plans for this yet.

You can use the tizen API using the tizen_interop.
Please see here
https://github.com/flutter-tizen/tizen_interop
https://docs.tizen.org/application/native/guides/connectivity/nsd/

**Comment by phuocbitmark** [comment]
Thank you
