### ISSUE TITLE
Trouble Installing Flutter-Tizen .tpk File on Tizen-OS Kiosk Device

### ISSUE THREAD

**Issue by syriani** [flutter-tizen/flutter-tizen#535]
I'm developing a Flutter-Tizen project for a Tizen-OS kiosk device, intended for internal use only. After building the project and obtaining the .tpk file, I'm attempting to transfer it to the kiosk device using the 'install from USB device' option. However, I keep encountering an error stating 'unable to find installation file.'

I'm confused about what exactly constitutes the installation file. Shouldn't it be the .tpk file I generated using the command 'flutter-tizen build tpk --device-profile tv'? Or do I need to include any additional files for the installation process?

Your insights would be greatly appreciated. Thank you!

**Comment by xuelian-bai** [comment]
hi, I'm not sure about kiosk device since we don't have one, but normally tpk file can't be installed from USB device for security reason on TV device, it may be the same for kiosk device.
You can install your tpk via device manager of tizen studio by sdb install command

**Comment by xuelian-bai** [comment]
When creating certificate, remember to add your device's duid to your certificate profile https://docs.tizen.org/application/dotnet/get-started/certificates/creating-certificates/

**Comment by syriani** [comment]
Thank you for response xuelian. But In my case I'm not physically close to the client who was the kiosk device meaning I have to send him the project as file and in this case I can't be a .tpk becuase of the device security reason. Do you know any other way that I can export a file from flutter-tizen other than .tpk and send it to the client?

**Comment by swift-kim** [comment]
What package type does the device expect? Is it `.wgt`? flutter-tizen only supports exporting app to the `.tpk` type.

**Comment by syriani** [comment]
To be honest I couldn't find what are the package type that the device is expected. but as far as I know the Operating system is Tizen 4.0. This is the device link: [https://www.samsung.com/us/business/support/owners/product/kma-series-digital-signage-km24a/
](url)

**Comment by swift-kim** [comment]
Related issue: https://github.com/flutter-tizen/flutter-tizen/issues/145

You may try changing the app language of your project to C++ by following [this section](https://github.com/flutter-tizen/flutter-tizen/wiki/Watch-app-development#changing-the-app-language) in case .NET (C#) development is not supported by the device. I'm not sure if it will work. If not, the only option is `.wgt` (web application) and you can't use Flutter in that case.

Also we have already removed support for Tizen 4.0 from our product (https://github.com/flutter-tizen/flutter-tizen/issues/481) so it might not be a good idea to use flutter-tizen to develop for the devices. (You may have to use old [releases](https://github.com/flutter-tizen/flutter-tizen/tags) like 3.10.1.)

**Comment by xuelian-bai** [comment]
If you want to use flutter-tizen for kiosk device, there are two ways to share your tpk:
1. Build your tpk with certificate which includes your client's device id, ask your client to install tizen studio on pc, connect to device and then sdb install your tpk
2. Build flutter-tizen web, then manually import into web app and build .wgt (It's a possible way, but kind of complicated)

As @swift-kim  mentioned, you need to use devices that have higher tizen version.

**Comment by syriani** [comment]
Thank you for your reply @xuelian-bai @swift-kim. Just a question can you provide a step by step process for how to open a tizen-flutter project inside the tizen studio because i tried and the tizen studio didn't read the project, and the client also comes from non-technical background. Thank you again!

**Comment by swift-kim** [comment]
VS Code is the way to go to write or edit Flutter app (Dart) code. 

Basically flutter-tizen is not intended for use with traditional Tizen IDEs (Tizen Studio/Visual Studio), but (technically) you can open the project file (`tizen/Runner.csproj`) in Visual Studio with the VS Tools for Tizen extension installed on Windows.
