### ISSUE TITLE
App crashes in case of conviva errors

### ISSUE THREAD

**Issue by Alexjk7777** [flutter-tizen/flutter-tizen#536]
Iam working on an ott application where we are using video__player_avplay pluggin for drm contents, but after intgrating conviva in case of any conviva errors app is getting crashed , need to know which all conviva version properly supports this pluggin is there any such limitation for flutter-tizen , or do we need to handle such errors from the app side

**Comment by xiaowei-guan** [comment]
@Alexjk7777 
I am responsible for developing the video_player_avplay plugin. First of all, thank you for using video_player_avplay plugin.
If you want to use video_player_avplay, please check out our documentation(https://github.com/flutter-tizen/plugins/tree/master/packages/video_player_avplay). video_player_avplay only support Tizen TV devices , and if you want to playback DRM content, the app must be signed with a partner-level certificate.
Can you share the steps to reproduce this issue or share the sample code? Thank you~

**Comment by Alexjk7777** [comment]
I was able to play the content properly using the pluggin ,but issue came after integrating conviva ,When i was swtching the contents faster while video play back is happening app crashes, Is there any limitations for this pluggin to use conviva with this ,

**Comment by xiaowei-guan** [comment]
Hello, I have checked with MM team, there is no limitations if you just call the player's interface.
Can you share your sample code? I will try to get crash stack information.
