### ISSUE TITLE
I cant find transformAlignment in AnimateContainer

### ISSUE THREAD

**Issue by oysterlab** [flutter-tizen/flutter-tizen#54]
Hi
I usually use transformAlignment property with transform of AnimationContainer. But I cant find it in flutter-tizen. I suspect it would be flutter versioning issue..

**Comment by swift-kim** [comment]
The property is available in Flutter 2.0.0 which was released a few days ago but flutter-tizen is still based on the previous stable version (1.22.6). The migration will be done in about 2 weeks. Thank you for your patience.
