### ISSUE TITLE
No certificate profile found. You can create one using the Certificate Manager.

### ISSUE THREAD

**Issue by AbirAppDevs** [flutter-tizen/flutter-tizen#555]
I am Facing a problem when flutter-tizen run cmd run in terminal. Its Shows 
``` attached image error 1:
target: tizen_dotnet_tpk
exception:Error: No certificate profile found. You can create one using the Certificate Manager.
```

ERROR 1:
<img width="497" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/f639b3c2-109a-4f8a-9c30-09c3325e9a47">

flutter-tizen doctor -v
<img width="496" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/ab461bb4-1353-4d13-907c-73a2fca86d95">
<img width="480" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/cba05886-6304-4906-88f6-ab3bd2340559">

And also tv emulator is not starting:

<img width="192" alt="updating the kerne" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/645083f9-a5c4-403e-b4ca-589e3f8a9478">
<img width="539" alt="updating the kerne2" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/78ec42b1-6857-4741-a95c-c3634dc675ad">

**Comment by JSUYA** [comment]
Hi, according to the error log, the certificate file does not exist. Please refer to the link in the log.
https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/install-tizen-sdk.md#create-a-certificate-profile
(Choose Samsung instead of Tizen as the profile type)

There are a few things to check when the emulator does not run.
It may be helpful to refer to the history of this issue. https://github.com/flutter-tizen/flutter-tizen/issues/546

**Comment by AbirAppDevs** [comment]
@JSUYA 
In My Case  turned off Memory integrity feature and also Hyper-V option is not enabled.

But Now It Shows T=Your System cannot support HW virtualization.

Screen Shots are here..

<img width="476" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/855e053d-2b43-4f0c-8167-647cd94debae">
<img width="387" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/6296aabe-524c-440b-b7c7-0f8ed2418c1c">
<img width="431" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/78f4fee0-b5fe-4cc0-a41d-c8092153e067">

**Comment by AbirAppDevs** [comment]
Hello @JSUYA  I solved my problem . Now Tizen TV Emulator run properly .
Here some screenshots..
<img width="594" alt="Screenshot 2024-06-06 125721" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/d54ddc0f-5eb9-41e7-8295-953967892fa3">
<img width="613" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/eabce411-152c-4936-8869-7049db8ff098">

But problem is after solving my problem here Another problem occurred in my android studio avd.  I cannot run emulator for HAXM issue .
<img width="555" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/0bc410bc-8d23-46e3-9d57-73d5641404e8">
 If I going to install HAXM , it shows error , but environment all are okay.
<img width="570" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/156082638/bc15d37c-71ea-466b-9d47-0a42d3202d67">

Do you have any idea for what this error showing?

**Comment by swift-kim** [comment]
https://developer.android.com/studio/run/emulator-acceleration#vm-deprecated

The documentation says that you don't need HAXM to run an Android 33.x+ emulator on an Intel processor.

> Starting from emulator 33.x.x.x, HAXM is deprecated as [Intel discontinues development of HAXM](https://github.com/intel/haxm). The Android Emulator hypervisor driver (AEHD) replaces Intel HAXM on Intel Processors.

Make sure your system support HW virtualization and install the right driver (either HAXM, AEHD, or Hyper-V). You should have a good understanding of your system.
