### ISSUE TITLE
Emulator is not running in Mac

### ISSUE THREAD

**Issue by MdAsifUrRahmanAbir** [flutter-tizen/flutter-tizen#558]
<img width="669" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/50311815/ea1d53a7-59ca-4c07-b3b8-a354f4a2824c">
<img width="269" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/50311815/38819caa-dc42-4b77-921c-d1960ac0a9f9">
<img width="642" alt="image" src="https://github.com/flutter-tizen/flutter-tizen/assets/50311815/05d8a764-a8e1-4eda-91f3-642834a130db">

**Comment by MdAsifUrRahmanAbir** [comment]
`hello@macs-MacBook-Pro ~ % kextstat | grep intel

Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
hello@macs-MacBook-Pro ~ % flutter-tizen doctor 
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.19.3, on macOS 14.0 23A344 darwin-x64,
    locale en-GB)
    ! Flutter version 3.19.3 on channel [user-branch] at
      /Users/hello/flutter-tizen/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Warning: `flutter` on your path resolves to
      /Users/hello/Developer/flutter/bin/flutter, which is not inside your
      current Flutter SDK checkout at /Users/hello/flutter-tizen/flutter.
      Consider adding /Users/hello/flutter-tizen/flutter/bin to the front of
      your path.
    ! Warning: `dart` on your path resolves to
      /usr/local/Cellar/dart/3.4.1/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/hello/flutter-tizen/flutter.
      Consider adding /Users/hello/flutter-tizen/flutter/bin to the front of
      your path.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss
      this error.
[✓] Tizen toolchain - develop for Tizen devices
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.`

**Comment by swift-kim** [comment]
You don't have HAXM installed on your mac. The following pages might be helpful.

https://github.com/intel/haxm/wiki/Installation-Instructions-on-macOS
https://developer.tizen.org/ko/development/tizen-studio/download/installing-tizen-studio/hardware-accelerated-execution-manager
