### ISSUE TITLE
Is it possible to customize screensaver content?

### ISSUE THREAD

**Issue by phuocbitmark** [flutter-tizen/flutter-tizen#567]
Dear team,
I'm developing a dotnet app on Tizen.
I wonder if there is a way to customize screen saver, in stead of OS default, i want to use some other "digital art" to play as screen saver.
If it is possible, could you give a hint which api to use?

Thank you.

**Comment by JSUYA** [comment]
> I wonder if there is a way to customize screen saver, in stead of OS default, i want to use some other "digital art" to play as screen saver.

As far as I know, there is no way to customize the default screen saver on a TV.

> If it is possible, could you give a hint which api to use?

If you have any questions about dotnet API, please ask here https://github.com/Samsung/TizenFX

**Comment by phuocbitmark** [comment]
@JSUYA thank you
