### ISSUE TITLE
Flutter-tizen behavior different from other platforms calling the keyboard (TextInput).

### ISSUE THREAD

**Issue by mattsouza26** [flutter-tizen/flutter-tizen#572]
When using TextInputType.none in a Flutter Tizen app, the on-screen keyboard still appears. This behavior is inconsistent with other platforms like Android and iOS, where the keyboard does not show with this configuration.

The issue persists even with a custom implementation of EditableTextState, where I explicitly create the TextInputConnection using TextInputType.none.

However, if I do not create the TextInputConnection, the physical keyboard does not work in the text field. This creates a conflict where it's impossible to achieve the desired behavior of disabling the on-screen keyboard while maintaining functionality for a physical keyboard.

**Comment by JSUYA** [comment]
Hi, thank you for your interest.
A patch has been merged to solve this issue. If you update flutter-tizen to the latest code and rerun it, you can see `TextInputType.none` working properly.
