### ISSUE TITLE
Layout dimensions don't change when keyboard is opened

### ISSUE THREAD

**Issue by j-troc** [flutter-tizen/flutter-tizen#70]
When following [Building beautiful UIs with Flutter codelab](https://codelabs.developers.google.com/codelabs/flutter#6) I've noticed a following issue.

It appears that layout dimensions do not take into account space taken by opened keyboard. This results in keyboard blocking part of the UI.

The codelab source code is available [here](https://github.com/flutter/codelabs/blob/master/friendly_chat/step_07/lib/main.dart)

The issue is present on both emulator and a device.

Result: 
![M-5 5-x86-2021-04-06-132754](https://user-images.githubusercontent.com/41898222/113704066-f3f73200-96db-11eb-84e2-726cc1622bf5.png)
![M-5 5-x86-2021-04-06-132737](https://user-images.githubusercontent.com/41898222/113704069-f5285f00-96db-11eb-9bab-52e5f32803ad.png)

Expected result:
![image](https://user-images.githubusercontent.com/41898222/113697803-fe153280-96d3-11eb-8ff8-ffa5e1481809.png)

**Comment by swift-kim** [comment]
This is a known issue that has to be addressed. The problem usually arises when we take both "screen rotation" and "showing a keyboard" into account together. The feature (resizing the screen when the keyboard is open) had previously been supported by the embedder (https://github.com/flutter-tizen/engine/pull/7), but was disabled and removed by https://github.com/flutter-tizen/engine/pull/28 and https://github.com/flutter-tizen/engine/pull/43. As TM1 and the mobile profile has reached the end of support so I believe this is not a critical issue, but still there are users who want to use the mobile emulator for testing during app development.
