### ISSUE TITLE
Text not rendering on samsung galaxy active watch 2

### ISSUE THREAD

**Issue by balvinderz** [flutter-tizen/flutter-tizen#72]
![WhatsApp Image 2021-04-07 at 1 02 33 PM (1)](https://user-images.githubusercontent.com/30950893/113828023-8f9ea600-97a1-11eb-8dcc-f8f104e08d98.jpeg)

Sample Code
`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget
{
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.red,
        body: Center(child: Column(
          children: [
            Image.asset("assets/flutter_icon.png"),
            Text("sojaasadaddd")
          ],
        )),
      ),
    );

  }
}`

**Comment by swift-kim** [comment]
Thanks for reporting! This looks like a regression introduced by https://github.com/flutter-tizen/engine/pull/40.

**Comment by balvinderz** [comment]
How to fix it for now ?

**Comment by swift-kim** [comment]
A quick workaround is to change the system font to any non-default font in the device settings.

**Comment by swift-kim** [comment]
Or to use custom fonts like [google_fonts](https://pub.dev/packages/google_fonts). The [gallery app](https://github.com/flutter/gallery) is working fine on watches because it uses a [TextTheme](https://github.com/flutter/gallery/blob/c5e0047f73376d4a2ee9149d9a698e825b0a2ff6/lib/themes/gallery_theme_data.dart#L86) based on google_fonts.

**Comment by luuksteitner** [comment]
Same problem on Galaxy watch 3. So far I haven't been able to figure out how to change the system font on this watch.

**Comment by swift-kim** [comment]
@flutter-tizen/maintainers Please take a look at this issue. This issue should be related to FontConfig (enabled by https://github.com/flutter-tizen/engine/pull/40) and the font resolution mechanism on Tizen (I don't know how it works). I'm not in the office this week so I can't test on devices.

**Comment by swift-kim** [comment]
The new engine release will be available in a few days. Thank you for your patience!
