### ISSUE TITLE
Engine artifacts should be downloaded when they are used

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#77]
Currently engine artifacts for each host platform (e.g. `linux-x64.zip` if on Linux) are cached by the launcher script before any Dart code is executed:

https://github.com/flutter-tizen/flutter-tizen/blob/7c339153df76295d754c0a3226de38c71dc1cb5b/bin/flutter-tizen#L140-L176

The zip archive size is only about 30 MB now so it doesn't make any big issue, but the size will be doubled if we enable arm64 builds of the engine in the near future. It would be better to separate artifacts for each target arch and download only when necessary (e.g. download x86 artifacts when building for emulator).

For the implementation, we may refer to `EngineCachedArtifact.updateInner()` in `package:flutter_tools/src/cache.dart`.

**Comment by swift-kim** [comment]
The size of the zip archive that contains arm64 artifacts is now about 60 MB. Is it still reasonable or should we split the file into 3~7?

https://github.com/flutter-tizen/engine/releases/tag/31279ea

**Comment by swift-kim** [comment]
We may also remove the python dependency of flutter-tizen by re-writing the logic in pure Dart and batch/shell script. Currently flutter-tizen depends on Python 3.6 or above only because the launcher script is written in python.

**Comment by WonyoungChoi** [comment]
@swift-kim How about writing the engine download logic in bash and powershell instead of the pure dart? I think we can use `curl` to download them in bash script.

**Comment by swift-kim** [comment]
@WonyoungChoi The launcher script cannot know which artifact will be used by the builder in advance. We can only remove the python dependency in that way and the artifact size will still remain large. Do you think it still makes sense?

**Comment by WonyoungChoi** [comment]
@swift-kim I agree, I'm gonna dig the similar parts of android build more.

**Comment by WonyoungChoi** [comment]
The artifacts can be separated into following files: 
- tizen-common.zip  (common/**)
- tizen-x86-debug.zip  (*.so)
- tizen-arm-debug.zip (*.so)
- tizen-arm-profile.zip (*.so)
- tizen-arm-profile_linux-x64.zip (linux-x64/gen_snapshot)
- tizen-arm-profile_darwin-x64.zip (darwin-x64/gen_snapshot)
- tizen-arm-profile_windows-x64.zip (windows-x64/gen_snapshot.exe)
- tizen-arm-release.zip (*.so)
- tizen-arm-release_linux-x64.zip (linux-x64/gen_snapshot)
- tizen-arm-release_darwin-x64.zip (darwin-x64/gen_snapshot)
- tizen-arm-release_windows-x64.zip (windows-x64/gen_snapshot.exe)
- tizen-arm64-debug.zip (*.so)
- tizen-arm64-profile.zip (*.so)
- tizen-arm64-profile_linux-x64.zip (linux-x64/gen_snapshot)
- tizen-arm64-profile_darwin-x64.zip (darwin-x64/gen_snapshot)
- tizen-arm64-profile_windows-x64.zip (windows-x64/gen_snapshot.exe)
- tizen-arm64-release.zip (*.so)
- tizen-arm64-release_linux-x64.zip (linux-x64/gen_snapshot)
- tizen-arm64-release_darwin-x64.zip (darwin-x64/gen_snapshot)
- tizen-arm64-release_windows-x64.zip (windows-x64/gen_snapshot.exe)

**Comment by swift-kim** [comment]
@WonyoungChoi FYI)

The gen_snapshots currently included in the releases are in fact downloaded from the google storage server (otherwise we need to set up dedicated Windows and macOS builds servers only for generating the snapshotters).

https://github.com/flutter-tizen/engine/blob/flutter-2.2.1-tizen/azure-pipelines.yml#L116

The number of above artifacts can be reduced by almost half, if we let the user download gen_snapshot directly from the google server.
