### ISSUE TITLE
Certificate errors on device.

### ISSUE THREAD

**Issue by allan175** [flutter-tizen/flutter-tizen#79]
I have followed all the set up steps and I can build/sign/run apps on my Galaxy Watch (Tizen 5.5) from the command line and via Tizen Studio.

However, "flutter-tizen run" goes through the build process then tries to install to the watch but gives the following output:-**flutter-tizen run**
Launching lib\main.dart on Tizen SM-R800 in debug mode...
The XXXXX profile is used for signing.
Building a Tizen application in debug mode...                     142.5s
Built build\tizen\com.example.flutter_test_1-1.0.0.tpk (16.7MB).
Installing build\tizen\com.example.flutter_test_1-1.0.0.tpk...        16.8s
Installing TPK failed with exit code 0:
WARNING: Your data are to be sent over an unencrypted connection and could be read by others.
pushed com.example.flutter_test_1-1.0.0.tpk       0%          0MB           0KB
pushed com.example.flutter_test_1-1.0.0.tpk     15%          2MB           0KB
pushed com.example.flutter_test_1-1.0.0.tpk     56%          9MB      4096KB
pushed com.example.flutter_test_1-1.0.0.tpk     82%         13MB     6399KB
pushed com.example.flutter_test_1-1.0.0.tpk     97%         16MB     1656KB
pushed com.example.flutter_test_1-1.0.0.tpk    100%        16MB     1656KB
1 file(s) pushed. 0 file(s) skipped.
...\flutter_test_1\build\tizen\com.example.flutter_test_1-1.0.0.tpk   2482KB/s (17560922 bytes in 6.909s)
path is /home/owner/share/tmp/sdk_tools/com.example.flutter_test_1-1.0.0.tpk
__return_cb req_id[1] pkg_type[tpk] pkgid[com.example.flutter_test_1] key[start] val[install]
__return_cb req_id[1] pkg_type[tpk] pkgid[com.example.flutter_test_1] key[install_percent] val[12]
__return_cb req_id[1] pkg_type[tpk] pkgid[com.example.flutter_test_1] key[install_percent] val[15]
__return_cb req_id[1] pkg_type[tpk] pkgid[com.example.flutter_test_1] key[install_percent] val[18]
__return_cb req_id[1] pkg_type[tpk] pkgid[com.example.flutter_test_1] key[install_percent] val[21]
__return_cb req_id[1] pkg_type[tpk] pkgid[com.example.flutter_test_1] key[install_percent] val[25]
__return_cb req_id[1] pkg_type[tpk] pkgid[com.example.flutter_test_1] key[install_percent] val[28]
__return_cb req_id[1] pkg_type[tpk] pkgid[com.example.flutter_test_1] key[error] val[-12] error message: :Invalid
certificate chain with certificate in signature.:<-3>
__return_cb req_id[1] pkg_type[tpk] pkgid[com.example.flutter_test_1] key[end] val[fail]
processing result : Check certificate error [-12] failed
spend time for pkgcmd is [9564]ms

**Comment by swift-kim** [comment]
I have no idea how this happens but did you try with another certificate? (Samsung certificate, not Tizen one)

**Comment by allan175** [comment]
Yes, this is with a Samsung certificate. I deleted my original ones, just in case I had the Tizen one by mistake.

**Comment by HakkyuKim** [comment]
Did you include the device DUID in the distributor certificate? (Was your watch device connected to your PC when you created the Samsung certificate?)

**Comment by allan175** [comment]
Yes to both.

My current certificates work with Tizen Studio and Tizen command line builds.

**Comment by swift-kim** [comment]
The flutter-tizen tool runs the following Tizen CLI command at the end of its build step to re-package a tpk with the user's profile (chain of certificates).
```sh
tizen package -t tpk -s [ProfileName] -- [PathToTpk]
```
You may try this manually from the command line (although it doesn't seem to help). The tpk in the path will be replaced with the new tpk and you can install it onto your device using:
```sh
sdb install [PathToTpk]
```
A side note: A tpk file is practically a zipped archive of all files/directories under `tpkroot` directory (which is located in your project's `build/tizen` after build). You can create a tpk from scratch by following these steps: (1) use `zip` (or any other archiving tool) to create a zip file, (2) change the file extension to `.tpk`, (3) re-package with your security profile using the above Tizen CLI command.

**Comment by swift-kim** [comment]
I encountered the same error when I was running a simple app on my new RPi4. When I choose a Tizen certificate I get a different error code (`key[error] val[-22] error message: :Unknown error code:<14>`). Still don't know why.

**Comment by allan175** [comment]
I'm not sure what your error is, but I think it's probably unrelated and this issue could be closed.

I'm not 100% sure what I did differently, but I deleted and got new certificates (via Tizen Studio) and it seems to be working now. I also think I had a mix-up with my CLI build and packaging and I thought it had worked when it could have picked up a previous package. After more testing I found I couldn't sign a CLI built package after all.

I made sure to delete all traces of my old certificates, then generated new ones via Tizen Studio and then told the CLI config where they were (via **tizen security-profiles** command). Then **flutter-tizen run** worked ok.

Sorry to have wasted your time!

**Comment by swift-kim** [comment]
No worries. That kind of thing could happen at any time when you're using the Tizen tooling. It just always sucks.

Anyway I'm glad your issue has been resolved!

**Comment by swift-kim** [comment]
I'll close this issue. If we happen to see this error again, we will have to try either:
- Go over the [security manager](https://github.com/Samsung/security-manager) source code (the latest source code is not publicly available)
- Run ["Permit to install applications"](https://github.com/Samsung/Wits/issues/90#issuecomment-752286114) (TV only)

**Comment by jtmuller5** [comment]
I'm getting the same error. Is there a way to configure the certificate that flutter-tizen uses? Each time I run it it tells me: 
The tpk has been signed with a default certificate. You can create one using Certificate Manager.
https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/install-tizen-sdk.md#create-a-tizen-certificate

I created a Samsung Certificate and a Tizen certificate but none of them are being used.

**Comment by swift-kim** [comment]
@jtmuller5 The only reason I can think of now is a corrupted manifest file. Could you check if your `~/tizen-studio-data/profile/profiles.xml` file exists and it contains below lines?

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles active="SomeProfileName" version="3.1">
<profile name="SomeProfileName">
<profileitem ca="..." distributor="0" key="..." password="..." rootca=""/>
<profileitem ca="..." distributor="1" key="..." password="..." rootca=""/>
<profileitem ca="" distributor="2" key="" password="" rootca=""/>
</profile>
...
```

The `flutter-tizen run` command always uses the current active profile for building tpk. You may try the `flutter-tizen build tpk` command which allows you to specify a specific profile name:

```sh
$ flutter-tizen build tpk --device-profile wearable --security-profile SomeProfileName
$ flutter-tizen install
```

**Comment by jtmuller5** [comment]
I actually got it to work based on a response in [this thread](https://developer.tizen.org/ko/forums/general-support/check-certificate-error-12-failed?langredirect=1).

I added a section like this to my *.csproj file:
```
<PropertyGroup>
 <AuthorPath>author_test.p12</AuthorPath>
 <AuthorPass>author_test</AuthorPass>
 <DistributorPath>tizen-distributor-signer.p12</DistributorPath>
 <DistributorPass>tizenpkcs12passfordsigner</DistributorPass>
</PropertyGroup>
```

**Comment by allan175** [comment]
I ended up getting the error again, and I now know what the actual problem was.

My set up is an SSH connection to a remote Ubuntu machine, and I do all my work via the command line.
The issue turned out to be caused by the Gnome Keyring not being unlocked because I had not unlocked it by, for example, opening a browser on the machine.

Connecting via remote desktop, opening the browser and unlocking the keyring, then closing the browser and disconnecting my remote desktop connection leaves the keyring unlocked and the flutter-tizen command will then operate properly until the machine is rebooted.

**Comment by swift-kim** [comment]
@allan175 Thank you for the information! I'll report to the Tizen SDK team if I manage to reproduce the issue and share the result here.

**Comment by swift-kim** [comment]
Hmm, I'm not sure how to reproduce the behavior exactly. I booted my Ubuntu without unlocking and connected via SSH. sdb isn't listing attached devices and I can't install any tpk.

**Comment by allan175** [comment]
Sorry, maybe because this issue is closed I didn't get a notification of your reply.

I wasn't able to build the TPK without unlocking the keyring. I don't think I tried listing or installing to devices.
